Add tests for DRIs in scala3doc
lampepfl/dotty pull request #10337
Opened 2020-11-16 13:16 UTC by Kordyjan

This PR adds tests for DRIs generated by doctool. Unique DRIs are crucial for linking inside the documentation to work properly. Fortunately, scala has rather strict rules for avoiding double definitions what makes declaring unique DRIs easy. Nevertheless, those tests have found at least 3 different problems with DRI generation. The cases verifying them are ignored or commented out. I'll open issues for each of them.

2020-11-18 12:37 UTC, romanowski requested changes
Beside those printlns code looks ok

2020-11-18 12:37 UTC, romanowski commented on scala3doc/test/dotty/dokka/linking/DriTest.scala
> +    if !duplicates.isEmpty then
`nonEmpty`

2020-11-18 12:37 UTC, romanowski commented on scala3doc/test/dotty/dokka/linking/DriTest.scala
> +      println()
why do we need `println`s here?

2020-11-18 12:46 UTC, Kordyjan commented on scala3doc/test/dotty/dokka/linking/DriTest.scala
> +      println()
Oops, that was for the debugging.

2020-11-19 09:16 UTC, romanowski approved these changes

2020-11-19 09:16 UTC, merged