Scripting
lampepfl/dotty pull request #10491
Opened 2020-11-25 14:29 UTC by anatoliykmetyuk

2020-12-11 08:59 UTC, nicolasstucki requested changes

2020-12-11 08:59 UTC, nicolasstucki commented on compiler/src/dotty/tools/scripting/ScriptingDriver.scala
> +        throw ScriptingException("More than one main method detected in your script")
We should tell which ones were found.

2020-12-11 08:59 UTC, nicolasstucki commented on compiler/test/dotty/tools/scripting/ScriptingTests.scala
> +            "-Yerased-terms",
Why did you need this one? I feel wrong to add it by default, users should opt-in to use this feature.

2020-12-11 08:59 UTC, nicolasstucki commented on compiler/src/dotty/tools/scripting/ScriptingDriver.scala
> +    val outDir = Files.createTempDirectory("scala3-scripting")
We should delete this directory after the script finishes

2020-12-11 08:59 UTC, nicolasstucki commented on compiler/src/dotty/tools/scripting/ScriptingDriver.scala
> +        else Nil
We can avoid the `null` with this refacroring
```scala
try 
  val method = cls.getMethod("main", classOf[Array[String]])
  if Modifier.isStatic(method.getModifiers) then List(method) else Nil
catch
  case _: java.lang.NoSuchMethodException => Nil
```

2020-12-11 08:59 UTC, nicolasstucki commented on compiler/src/dotty/tools/scripting/ScriptingDriver.scala
> +      file <- outDir.toFile.listFiles.toList
```suggestion
      file <- outDir.toFile.listFiles.toIterator
```
or some other way to get the iterator from java to scala

2020-12-11 09:01 UTC, nicolasstucki commented
We are also missing some docs.

2020-12-11 14:44 UTC, nicolasstucki approved these changes

2020-12-11 18:43 UTC, merged

2020-12-11 21:43 UTC, philwalk commented
I have used scala for several years, and make heavy use of scala scripting.   I am eager to contribute to this and have some ideas to greatly improve the user experience for new users.

2020-12-11 22:51 UTC, som-snytt commented
This will make it much easier to run quick test comparisons between Scala 2 and 3!

2020-12-16 12:04 UTC, rjolly commented
I have a dream that `scala` is just a shorthand for
```scala
jrunscript -cp lib/scala3-compiler_3.0.0-M3.jar:lib/scala3-library_3.0.0-M3.jar:lib/scala3-interfaces-3.0.0-M3.jar:lib/tasty-core_3.0.0-M3.jar:lib/scala-library-2.13.4.jar:lib/scala-asm-7.3.1-scala-1.jar -Djava.class.path=lib/scala3-library_3.0.0-M3.jar:lib/scala-library-2.13.4.jar -l scala
```