Remove deprecated warning in synthetic def
lampepfl/dotty pull request #11055
Opened 2021-01-11 07:18 UTC by changvvb

2021-01-11 11:10 UTC, bishabosha requested changes
Thank you for opening this PR, I will link to this comment on why we need to be careful with ignoring synthetic defs which I see you already protect against some cases: https://github.com/lampepfl/dotty/pull/10996#issuecomment-754680777

2021-01-11 11:10 UTC, bishabosha commented on compiler/src/dotty/tools/dotc/typer/RefChecks.scala
> +      if sym.isEnum then ctx.owner.ownersIterator.exists(isDeprecatedOrEnum)
I believe it is still simpler to put the if condition inside the argument to `exists`

2021-01-11 11:10 UTC, bishabosha commented on compiler/src/dotty/tools/dotc/typer/RefChecks.scala
> +    def isDeprecatedOrSyntheticMethod(owner: Symbol) = owner.isDeprecated || (owner.isRealMethod && owner.is(Synthetic))
a call to this method should replace the first condition of `isDeprecatedOrEnum`

2021-01-11 11:48 UTC, bishabosha commented on compiler/src/dotty/tools/dotc/typer/RefChecks.scala
> +      ctx.owner.ownersIterator.exists(if sym.isEnumCase then isDeprecatedOrEnum else isDeprecatedOrSyntheticMethod)
`isDeprecatedOrEnum` still needs to call `isDeprecatedOrSyntheticMethod`, the condition here was just to lift the check out of the loop

2021-01-11 12:53 UTC, changvvb commented
> Thank you for opening this PR, I will link to this comment on why we need to be careful with ignoring synthetic defs which I see you already protect against some cases: https://github.com/lampepfl/dotty/pull/10996#issuecomment-754680777

@bishabosha I want to know some cases that we should warn in synthetic scope

2021-01-11 14:01 UTC, smarter commented
> I want to know some cases that we should warn in synthetic scope

I mentioned some cases in https://github.com/lampepfl/dotty/pull/10996#issuecomment-754680777, as far as I can tell this PR has the same issues as https://github.com/lampepfl/dotty/pull/10996 and should be rejected for the same reason in favor of what I suggested in https://github.com/lampepfl/dotty/pull/10996#issuecomment-754719014

2021-01-11 15:57 UTC, changvvb commented
I checked these cases and got the following results:
```scala
@deprecated("no CaseClass", "0.1") case class CaseClass(rgb: Int)

object Test {

  abstract class TestX

  val x = new TestX {
    val obj = new CaseClass(5) // warn
  }

  val y = Option(5).map(new CaseClass(_)) // warn
  val z = CaseClass(4)  // not warn but seems not related with this PR
}
```

But I agree that should not check synthetic flag only.

2021-01-11 16:22 UTC, changvvb commented
@bishabosha @smarter Is it possible to check the `sourcePos` of ctx owners? we can check whether exists owner `sourcePos` that 
1.  is not `<no position>`
2. is not `sourcePos` of the deprecated symbol.

I think the user code must have a valid `sourcePos` right?

2021-01-12 07:53 UTC, changvvb commented
> @bishabosha @smarter Is it possible to check the `sourcePos` of ctx owners? we can check whether exists owner `sourcePos` that
> 
> 1. is not `<no position>`
> 2. is not `sourcePos` of the deprecated symbol.
> 
> I think the user code must have a valid `sourcePos` right?

This is not a good solution because should disable not only `deprecated` warnings but also other warnings in synthetic scope.

2021-01-12 07:53 UTC, closed without merging