Migrate away from dokka: Part 1
lampepfl/dotty pull request #11183
Opened 2021-01-20 23:17 UTC by romanowski

2021-01-25 10:37 UTC, BarkingBad approved these changes
Good work!

2021-01-25 10:37 UTC, BarkingBad commented on scala3doc/src/dotty/renderers/Writter.scala
> +trait Writter(using ctx: DocContext) extends Locations:
Is it intentional to have double `t` in `Writter`, or is it typo?

2021-01-27 09:10 UTC, BarkingBad requested changes

2021-01-27 09:10 UTC, BarkingBad commented on scala3doc/src/dotty/dokka/model/api/api.scala
> +  def deprecated: Option[Annotation] =
This will probably conflict with that PR https://github.com/lampepfl/dotty/pull/11216 Though I can resolve conflicts on my own

2021-01-27 09:10 UTC, BarkingBad commented on scala3doc/src/dotty/renderers/Writter.scala
> +trait Writer(using ctx: DocContext) extends Locations:
Still there is typo in filename :P

2021-01-27 09:10 UTC, BarkingBad commented on scala3doc/src/dotty/renderers/html.scala
> +  val h5 = Tag("h4")
`Tag("h5")`

2021-01-27 09:10 UTC, BarkingBad commented on scala3doc/src/dotty/renderers/html.scala
> +  val h6 = Tag("h4")
`Tag("h6")`

2021-01-27 09:10 UTC, BarkingBad commented on scala3doc/src/dotty/dokka/model/api/api.scala
> +  def deprecated: Option[Annotation] =
Note to myself, not CR

2021-01-28 10:41 UTC, pikinier20 commented on scala3doc/src/dotty/renderers/HtmlRenderer.scala
> +      .filter(m => m.origin == Origin.RegularlyDefined && m.inheritedFrom.isEmpty)
There was a function that decided whether to render page for member or not (Kind.Package and Kind.Classlike can be nested in e.g. Kind.Given). Without checking nested kinds we don't generate pages for all members that should have page.

It should look like
```Scala
    def filterFunc(kind: Kind): Boolean = kind match {
      case Kind.Package => true
      case _ if kind.isInstanceOf[Classlike] => true
      case Kind.Given(inner, _, _) => filterFunc(inner)
      case Kind.EnumCase(inner) => filterFunc(inner)
      case _ => false
    }
    val childrenPages = member
      .membersBy(m => filterFunc(m.kind))
      .filter(m => m.origin == Origin.RegularlyDefined && m.inheritedFrom.isEmpty)
```

2021-01-29 15:09 UTC, BarkingBad approved these changes

2021-01-30 12:57 UTC, merged