add support for ToExpr[Class[_]]
lampepfl/dotty pull request #11206
Opened 2021-01-24 22:34 UTC by Jasper-M

This is a suggestion in response to this StackOverflow question: https://stackoverflow.com/q/65869784/1374461

If we want to support instances for wildcard types in general we might want to review other given instances as well.

2021-01-25 14:15 UTC, nicolasstucki requested changes
We should have a test with the code example in StackOverflow

2021-01-27 12:27 UTC, nicolasstucki approved these changes

2021-01-27 13:33 UTC, nicolasstucki commented
We will need to rebase to make the CI pass.

2021-01-27 13:35 UTC, Jasper-M commented
> We will need to rebase to make the CI pass.

Aha. I was just meaning to ask if I should.

2021-01-28 10:38 UTC, merged