Add support for anchors to old scaladoc and javadoc
lampepfl/dotty pull request #11564
Opened 2021-03-01 09:10 UTC by pikinier20

closes #11085

2021-03-01 12:25 UTC, romanowski requested changes

2021-03-01 12:25 UTC, romanowski commented on scaladoc/src/dotty/tools/scaladoc/tasty/JavadocAnchorCreator.scala
> +    case AppliedType(tpe, typeList) => transformPrimitiveType(tpe.show)
Can we compare symbols or types here? Output of `show` is not guaranteed to be stable.

2021-03-01 12:25 UTC, romanowski commented on scaladoc/src/dotty/tools/scaladoc/tasty/SymOps.scala
> +            Option(csym.associatedFile).map(_.path).flatMap( path =>
Did you notice any slowdown after these changes? especially this line may affect performance so we may consider caching (this needs to be tested with scala 3 doc not, the `self` one)

2021-03-01 12:25 UTC, romanowski commented on scaladoc/src/dotty/tools/scaladoc/tasty/SymOps.scala
> +        val location = className.fold(sym.packageName)(cn => s"${sym.packageName}.${cn}")
I think we can work with Seq[Sring] rather then concatenate and then split it later on in each branch

2021-03-04 13:21 UTC, romanowski approved these changes

2021-03-05 11:22 UTC, BarkingBad approved these changes

2021-03-05 11:35 UTC, merged