Print singleton types like in source
lampepfl/dotty pull request #11672
Opened 2021-03-09 15:54 UTC by nicolasstucki

* Print singleton in a for that users can recognize
* Print extra type information as comments (only if needed)
* Print missing Double and Float type information

Fixes #9883

Based on code from #11135

Printed types

```diff
- (true: Boolean) | ("abc": String) | (1: Int) | (2L: Long) | (1.0: Double) | (1.3: Float) | ('c': Char) | (x: Int)       | (3: Byte)  | (4: Short)
+ true            | "abc\"          | 1        | 2L         | 1.0d          | 1.3f         | 'c'         | x.type /*Int*/ | 3 /*Byte*/ | 4 /*Short*/
```

2021-03-10 22:03 UTC, odersky requested changes
I think that the current way is actually nicer, in most cases. So I would not change this unless we get a lot more experience that makes us decide otherwise.

2021-03-10 22:07 UTC, odersky reviewed
Going though the error messages I find the previous way better in all cases. Do I vote to drop this.

2021-03-10 22:07 UTC, odersky commented on tests/neg-custom-args/explicit-nulls/byname-nullables.check
> +   |                        Found:    x.type /*String | Null*/
Clearly the old message is better. Non-experts would not know what x.type even is!

2021-03-10 22:07 UTC, odersky commented on tests/neg-custom-args/explicit-nulls/byname-nullables.check
> -   |                      match arguments (String | Null, (1 : Int))
On the fence here, but I tend to find the old way better

2021-03-10 22:07 UTC, odersky commented on tests/neg-custom-args/fatal-warnings/i9408a.check
> +   |The conversion Test11.a2foo.type /*[A] => A => Test11.Foo*/ will not be applied implicitly here in Scala 3 because only implicit methods and instances of Conversion class will continue to work as
Old way better in each case here

2021-03-10 22:07 UTC, odersky commented on tests/neg-custom-args/fatal-warnings/i9408b.check
> +  |The conversion test.conversions.Conv.implicitLength.type /*String => Int*/ will not be applied implicitly here in Scala 3 because only implicit methods and instances of Conversion class will conti
Ditto

2021-03-11 08:29 UTC, nicolasstucki commented
I identified that we use the same printer logic for two disi

2021-03-11 08:29 UTC, closed without merging

2021-03-11 08:32 UTC, nicolasstucki commented
Doing this I identified that we use the same printing logic for two quite distinct cases. The first is to print a type as a type that is written in source, that is the usecase that becomes less intelligible too users. Then the second case is to print the type as a path and its underlining type, the current printer is aligned with this representation.