Fix hljs highlighting for safari browser
lampepfl/dotty pull request #11772
Opened 2021-03-16 13:22 UTC by BarkingBad

2021-03-16 14:45 UTC, BarkingBad commented
Before:
![obraz](https://user-images.githubusercontent.com/32793002/111328106-3d6cd800-866e-11eb-9417-c5e61c17e834.png)
After:
![obraz](https://user-images.githubusercontent.com/32793002/111328149-478ed680-866e-11eb-8769-0910483455c7.png)

A tried to change regexes to be `look behind` free as safari browser doesn't support that yet. I used a trick proposed [here](https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group/51568859). Could you @TheElectronWill look into them whether they are correct?

2021-03-17 09:57 UTC, TheElectronWill commented on scaladoc/resources/dotty_res/scripts/hljs-scala3.js
> +      begin: `((?:${name} )(${id.source})`
missing parenthesis?

2021-03-17 10:12 UTC, TheElectronWill commented
I'm afraid this simple fix won't work.

- changing `id` this way highlights the method names incorrectly: in `def func_=` the `=` will not be included in the function's name  
- changing `titleFor` breaks the highlighting of "titles", i.e. the names of variables and methods aren't highlighted anymore.
example:
![image](https://user-images.githubusercontent.com/10965722/111451197-7611bd80-8711-11eb-93f2-42ecf58ae77a.png)
becomes
![image](https://user-images.githubusercontent.com/10965722/111451261-888bf700-8711-11eb-9bbd-1e4cddac5399.png)

- changing `ENUM_CASE` changes how cases are detected, they end up as `type` instead of `title`. And in `case A, B`, `A` and `B` won't be labelled the same way. 
- changing the markdown links this way includes the label into the url, which is a bit weird semantically. If you underline the links you see the difference : 
  ![image](https://user-images.githubusercontent.com/10965722/111450712-f552c180-8710-11eb-8096-691f868d1022.png) becomes ![image](https://user-images.githubusercontent.com/10965722/111450968-364ad600-8711-11eb-8884-75703933fae2.png)

2021-03-17 10:25 UTC, TheElectronWill requested changes
There should be a better way of avoiding the look-behinds. I'll try some workarounds :slightly_smiling_face: 
[Related discussion in hljs repo](https://github.com/highlightjs/highlight.js/issues/2520)

2021-03-18 09:31 UTC, BarkingBad commented
> I'll try some workarounds

Would you like to overtake that issue?

2021-03-18 09:59 UTC, TheElectronWill commented
> > I'll try some workarounds
> 
> Would you like to overtake that issue?

I'll be glad to do it! I'll assign myself

2021-03-18 10:08 UTC, BarkingBad commented
No problem, thank you for your support :D 

I think we can close that PR since it's on my fork and it would be hard to cooperate, and when you are ready, you'll open a fresh new one. I'll assign you to the related issue #11771

2021-03-18 10:08 UTC, closed without merging