fix #9276: check valdef is realizable at pickler
lampepfl/dotty pull request #11843
Opened 2021-03-22 14:00 UTC by bishabosha

fixes #9276

2021-03-22 14:06 UTC, bishabosha commented
I will repost this comment here:
https://github.com/lampepfl/dotty/issues/9276#issuecomment-804087804

2021-03-22 14:20 UTC, smarter commented
test performance please

2021-03-22 14:32 UTC, bishabosha commented on compiler/src/dotty/tools/dotc/core/tasty/TreePickler.scala
> +        case _: ValDef if !sym.is(StableRealizable) =>
should probably check the tag instead

2021-03-22 20:26 UTC, odersky commented
test performance please

2021-03-22 20:40 UTC, odersky commented
The problem with this is: checking realizability is usually cheap but has unbounded complexity for lazy vals. We sort of rely on the fact that the intersection of (non-object) lazy vals and vals with type members (where we check stability) is usually small. But with this PR that consideration is now invalid; we will check realizability for every val, at possibly unbounded cost. So, that makes me nervous, even if our benchmarks don't show it.

2021-03-22 22:25 UTC, odersky requested changes
I think in summary the potentially unbounded slowdowns weigh more heavily than the potential gains

2021-03-23 17:16 UTC, closed without merging

2021-03-23 17:16 UTC, bishabosha commented
close in favor of #11858