Correct generic signature for intersection involving Array
lampepfl/dotty pull request #12205
Opened 2021-04-23 13:37 UTC by smarter

We can't just check the class symbol since both `Array[Int]` and
`Array[String]` have the same symbol but different erasure.

Fixes #12204.

2021-04-23 14:23 UTC, michelou commented
> We can't just check the class symbol since both `Array[Int]` and
> `Array[String]` have the same symbol but different erasure.
> 
> Fixes #12204.

@smarter Possible candidate for a RC4 or the timeline would be too short to get the 3.0.0-final out for [Scalacon 2021](https://skillsmatter.com/conferences/13319-scalacon-2021) ?!

2021-04-23 14:29 UTC, smarter commented
This is just about calls from Java and only an issue for a type whose only value is `null`, so not critical at all and not worth backporting.

2021-05-10 23:06 UTC, bishabosha requested changes
While the fix works for the given example, there is also a mismatch when the array parameters are for value classes:
```scala
class A
class B

class VC1(val toStr: A) extends AnyVal
class VC2(val toInt: B) extends AnyVal

class Z {
  def ARRAY_132(x: Array[VC1] with Array[VC2]): Unit = {}
}
```

this produces a generic signature `(x: A[]): void` and descriptor `(x: VC1[]): void`

2021-05-10 23:13 UTC, smarter commented
Isn't that a special case of the separate issue https://github.com/lampepfl/dotty/issues/12189 ?

2021-05-11 08:44 UTC, merged