Store GADT constraints until PostTyper
lampepfl/dotty pull request #12258
Opened 2021-04-28 12:08 UTC by abgruszecki

In some cases, the attachment can get dropped. We have a lot of such cases. Most seem to happen for tuple patterns.

2021-04-28 12:09 UTC, smarter commented on compiler/src/dotty/tools/dotc/typer/Typer.scala
> +  val InferredGadtConstraints = new Property.Key[core.GadtConstraint]
This should be a StickyKey to not get lost through tree transformations:
```suggestion
  val InferredGadtConstraints = new Property.StickyKey[core.GadtConstraint]
```

2021-04-28 12:44 UTC, smarter commented on compiler/src/dotty/tools/dotc/transform/PostTyper.scala
> +           pat.getAttachment(typer.Typer.InferredGadtConstraints) match
If they're not used afterwards we don't want to keep them around:
```suggestion
           pat.removeAttachment(typer.Typer.InferredGadtConstraints) match
```

2021-04-28 12:45 UTC, smarter commented on compiler/src/dotty/tools/dotc/typer/Typer.scala
> +      pat1.putAttachment(InferredGadtConstraints, ctx.gadt)
We should only do this if the gadt constraint is non-empty

2021-04-29 07:53 UTC, odersky commented
test performance please

2021-04-29 07:56 UTC, odersky requested changes
I am wary that this could give bad memory leaks. GADT constraints can be large.

Why do we need GADT constraints in PostTyper? The PR does not explain, nor does the code.

2021-04-29 08:51 UTC, abgruszecki commented
@odersky there's a serious problem - type application that needs GADT constraints simply doesn't work. https://github.com/lampepfl/dotty/issues/12226 is one example. Another one is that without this PR we get an error on this line: https://github.com/lampepfl/dotty/pull/12258/files#diff-953aaf705b431c6945ad2bd63ce89e017169f7373c45f9c40f265f4d11705a81R11.

The reason why type application doesn't work is that we check it in PostTyper, when we already forgot the GADT constraints. I tried moving the checks to Typer, but it seems like there's no clean way to do that, for instance b/c when we exit `typedTypeApply`, the type arguments may still be variables. So that means we should either re-infer the constraints in PostTyper, or store and extract them. Of those two solutions, storing the constraints is by far the cleanest and the most future-proof.

If we ever get problems because of too many GADT constraints, we could simply infer less of them. It's always sound to infer less GADT constraints. IIRC, GHC also stores its GADT constraints, and won't record constraints past some threshold.

2021-04-29 12:01 UTC, odersky commented
OK. I'd just add a comment explaining why we need to attach GADT constraints

2021-04-29 15:51 UTC, smarter approved these changes

2021-04-29 16:54 UTC, merged