Fix #12260: Add underscore to match type syntax
lampepfl/dotty pull request #12261
Opened 2021-04-28 15:09 UTC by OlivierBlanvillain

Also subsumes #9172 by fixing #9171.

2021-04-29 10:27 UTC, odersky commented
`simplify` is _very_ costly. So we do it once when we generate types. Why is it needed in type constant folding? We should try to avoid it there, or some code that constant folds a lot might blow up in complexity.

2021-04-29 12:57 UTC, OlivierBlanvillain commented
I opened #12278 to discuss simplify separately, it's orthogonal to this PR.

2021-05-01 16:59 UTC, odersky requested changes

2021-05-01 16:59 UTC, odersky commented on compiler/src/dotty/tools/dotc/parsing/Parsers.scala
> +            scalaAny
We usually avoid generating code that does not exist like that in source in Parser, since it will confuse IDEs. Why not `Ident(nme.WILDCARD)`?

2021-05-01 16:59 UTC, odersky commented on tests/neg/matchtype-seq.check
> +   |                        case Any => String
I think those should be `_ => String` since that was what's written.

2021-05-26 14:11 UTC, odersky commented on compiler/src/dotty/tools/dotc/core/Types.scala
> +    object WildcardPattern {
why that particular encoding?

2021-05-26 14:11 UTC, odersky commented on compiler/src/dotty/tools/dotc/parsing/Parsers.scala
> +            typeBounds().withSpan(Span(start, in.lastOffset, start))
Maybe just use Ident(`_`)?

2021-05-26 14:11 UTC, odersky commented on compiler/src/dotty/tools/dotc/core/Types.scala
> +    object WildcardPattern {
Could we just use a fresh TypeVar as the pattern type? Or `Any`? Are higher-kinded matches the problem here?

2021-07-29 15:41 UTC, SethTisue commented
What's the status of `case ?`?

If I understand correctly, there's three ways to write the same thing: `case ?`, `case _`, and `case Any`, and they are all intended to be synonymous? Is one of them considered preferred style?

In term-level matches, under `-source:future` I'm expected to write e.g. `case xs: List[?]` rather than `case _: List[_]`, so this sets an expectation that the way to write "any type, I don't care" is `?`, not `_`. If so, why support `case _`?

(I don't have any firm opinions about this, I'm just asking questions...)

2021-07-29 20:40 UTC, OlivierBlanvillain commented
> If I understand correctly, there's three ways to write the same thing: case ?, case _, and case Any, and they are all intended to be synonymous?

Yes, they are 3 equivalant ways to write catch-all patterns for match types. The situation is actually symetrical between term and type level:

```scala
def foo(x) = x match
  case _ =>
  case _: Any =>
  case _: ? => // Unlike scalac which complains with
               // "error: unbound wildcard type",
               // Dotty is perfectly fine with this...
```

```scala
type Foo[X] = X match
  case _ =>
  case Any =>
  case ? =>
```

> Is one of them considered preferred style?

I like `case _ =>` for the symmetry, but it's just my personal preference :)

2021-07-29 21:08 UTC, som-snytt commented
Previous missed opportunity was to accept `case if expr =>` and perhaps `case =>`. Now that seems less weird.

I sense a pun on "Casey at the Bat" coming on. "There is no joy in Matchville."

2021-07-29 21:11 UTC, dwijnand commented
> Yes, they are 3 equivalant ways to write catch-all patterns for match types. The situation is actually symetrical between term and type level:

Those aren't equivalent though: in the match expression it's switching from terms to types, while in match types it's types only.  So I feel like either embrace the symmetry with match expressions and make `case _ =>` the "symbolic" catch all, or we embrace that `?` as the symbol for 🤷🏼 and deprecate `case _ =>`.  3 options seems unnecessary to me.

2021-07-30 08:31 UTC, OlivierBlanvillain commented
IMO a standalone `?` type looks a bit weird visually (compared to `Foo[?]`, where it's pretty clear what's going on). So maybe we should follow scalac and disallow "unbound wildcard type"...

> So I feel like we either embrace the symmetry with match expressions and make case _ => the "symbolic" catch all

I'm not sure what you mean by that, can you elaborate?

2021-07-30 12:33 UTC, dwijnand commented
> > So I feel like we either embrace the symmetry with match expressions and make case _ => the "symbolic" catch all
> 
> I'm not sure what you mean by that, can you elaborate?

As one of the two alternatives I was saying, in this alternative we don't use `?` at the type level, but continue to use `case _ =>`, like it's used in match expressions - which implies deprecating and removing `case ? =>`.  Which, IIUC, matches your preference:

> I like `case _ =>` for the symmetry, but it's just my personal preference :)

2021-07-31 08:24 UTC, OlivierBlanvillain commented
The community build fails without the `case ? =>` ([it's used in scodecs](https://github.com/scodec/scodec/blob/c568b493f5359ee1f43b979205150ebbdeb5ddfa/shared/src/main/scala/scodec/DropUnits.scala#L39)). I propose to move that discussion to a separate issue.

2021-09-23 09:21 UTC, OlivierBlanvillain commented
rebased

2021-11-01 10:17 UTC, bishabosha commented
New issue that would be fixed by this: https://github.com/lampepfl/dotty/issues/13855

2022-01-23 17:48 UTC, odersky approved these changes

2022-01-23 17:49 UTC, merged