Upgrade Dotty Reference to 3.0.0
lampepfl/dotty pull request #12464
Opened 2021-05-13 15:35 UTC by anatoliykmetyuk

2021-05-14 17:29 UTC, smarter commented
fs2 fails (I don't see how this could be related to this change so it's likely flakey?) /cc @mpilquist:
```scala
[error] ==> X fs2.StreamCombinatorsSuite.groupWithin - accumulation and splitting  0.481s munit.ComparisonFailException: /__w/dotty/dotty/community-build/community-projects/fs2/core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala:851
[error] 850:        .toList
[error] 851:        .assertEquals(expected)
[error] 852:    }
[error] values are not the same
[error] => Obtained
[error] List(
[error]   List(
[error]     1,
[error]     2,
[error]     3
[error]   ),
[error]   List(
[error]     4
[error]   ),
[error]   List(
[error]     5,
[error]     6,
[error]     7,
[error]     8,
[error]     9
[error]   ),
[error]   List(
[error]     10,
[error]     11,
[error]     12,
[error]     13,
[error]     14
[error]   ),
[error]   List(
[error]     15,
[error]     16,
[error]     17,
[error]     18,
[error]     19
[error]   ),
[error]   List(
[error]     20,
[error]     21,
[error]     22
[error]   )
[error] )
[error] => Diff (- obtained, + expected)
[error]    List(
[error] -    4
[error] -  ),
[error] -  List(
[error] +    4,
[error]      5,
[error]      7,
[error] -    8,
[error] -    9
[error] +    8
[error]    ),
[error]    List(
[error] +    9,
[error]      10,
[error]      12,
[error] -    13,
[error] -    14
[error] +    13
[error]    ),
[error]    List(
[error] +    14,
[error]      15,
[error]      17,
[error] -    18,
[error] -    19
[error] +    18
[error]    ),
[error]    List(
[error] +    19,
[error]      20,
[error]     at munit.FunSuite.assertEquals(FunSuite.scala:11)
[error]     at munit.CatsEffectAssertions.assertIO$$anonfun$2$$anonfun$1(CatsEffectAssertions.scala:49)
[error]     at cats.effect.IO$.apply$$anonfun$1(IO.scala:806)
[error]     at cats.effect.IOFiber.runLoop(IOFiber.scala:270)
[error]     at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1132)
[error]     at cats.effect.IOFiber.run(IOFiber.scala:126)
[error]     at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:384)
[error] Failed: Total 1447, Failed 1, Errors 0, Passed 1428, Skipped 18
[error] Failed tests:
[error] 	fs2.StreamCombinatorsSuite
```

2021-05-14 18:35 UTC, mpilquist commented
Definitely an intermittent failure in fs2 test suite. I’ll mark it flaky later which will prevent it from causing a build failure.

> On May 14, 2021, at 1:29 PM, Guillaume Martres ***@***.***> wrote:
> 
> ﻿
> fs2 fails (I don't see how this could be related to this change so it's likely flakey?) /cc @mpilquist:
> 
> [error] ==> X fs2.StreamCombinatorsSuite.groupWithin - accumulation and splitting  0.481s munit.ComparisonFailException: /__w/dotty/dotty/community-build/community-projects/fs2/core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala:851
> [error] 850:        .toList
> [error] 851:        .assertEquals(expected)
> [error] 852:    }
> [error] values are not the same
> [error] => Obtained
> [error] List(
> [error]   List(
> [error]     1,
> [error]     2,
> [error]     3
> [error]   ),
> [error]   List(
> [error]     4
> [error]   ),
> [error]   List(
> [error]     5,
> [error]     6,
> [error]     7,
> [error]     8,
> [error]     9
> [error]   ),
> [error]   List(
> [error]     10,
> [error]     11,
> [error]     12,
> [error]     13,
> [error]     14
> [error]   ),
> [error]   List(
> [error]     15,
> [error]     16,
> [error]     17,
> [error]     18,
> [error]     19
> [error]   ),
> [error]   List(
> [error]     20,
> [error]     21,
> [error]     22
> [error]   )
> [error] )
> [error] => Diff (- obtained, + expected)
> [error]    List(
> [error] -    4
> [error] -  ),
> [error] -  List(
> [error] +    4,
> [error]      5,
> [error]      7,
> [error] -    8,
> [error] -    9
> [error] +    8
> [error]    ),
> [error]    List(
> [error] +    9,
> [error]      10,
> [error]      12,
> [error] -    13,
> [error] -    14
> [error] +    13
> [error]    ),
> [error]    List(
> [error] +    14,
> [error]      15,
> [error]      17,
> [error] -    18,
> [error] -    19
> [error] +    18
> [error]    ),
> [error]    List(
> [error] +    19,
> [error]      20,
> [error]     at munit.FunSuite.assertEquals(FunSuite.scala:11)
> [error]     at munit.CatsEffectAssertions.assertIO$$anonfun$2$$anonfun$1(CatsEffectAssertions.scala:49)
> [error]     at cats.effect.IO$.apply$$anonfun$1(IO.scala:806)
> [error]     at cats.effect.IOFiber.runLoop(IOFiber.scala:270)
> [error]     at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1132)
> [error]     at cats.effect.IOFiber.run(IOFiber.scala:126)
> [error]     at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:384)
> [error] Failed: Total 1447, Failed 1, Errors 0, Passed 1428, Skipped 18
> [error] Failed tests:
> [error] 	fs2.StreamCombinatorsSuite
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-05-15 18:39 UTC, smarter requested changes
Now that https://github.com/lampepfl/dotty/pull/12371 is merged, we should at the same time as we bump the referenceVersion bump the `previousDottyVersion`

2021-05-17 08:15 UTC, anatoliykmetyuk commented
Rebased on `master`.

Currently `previousDottyVersion` and `previousDottyBinaryVersion` are already set to `3.0.0-RC3` – is that not correct?

2021-05-17 08:43 UTC, smarter commented
It should be set to the latest published version (and the whitelist in project/MiMaFilters.scala should be cleared every time it's updated), so it should be 3.0.0 (which is identical to 3.0.0-RC3 so we won't clear the whitelist this time)

2021-05-17 13:18 UTC, smarter requested changes

2021-05-17 13:18 UTC, smarter commented on project/Build.scala
> +  val previousDottyBinaryVersion = "3.0.0"
The binary version is 3 now (can just be hardcoded in the single place where it's used)

2021-05-18 10:59 UTC, merged