Rename documentation references of 'compilation unit' to 'source file'.
lampepfl/dotty pull request #12481
Opened 2021-05-14 17:33 UTC by megri

This includes everything under the /docs folder and nothing else: sources and scaladoc still refer to 'compilation unit'

2021-05-18 11:40 UTC, OlivierBlanvillain approved these changes

2021-05-18 11:47 UTC, som-snytt commented
It's OK for popular literature, but if they took my idea to take a directory of files as a single compilation unit, then obviously the equivalence would fail. (People complained that if companions have to be in a single file, then the file gets too big. Why can't it be two files.)

2021-05-26 07:13 UTC, odersky requested changes
OK with the change for user-facing docs but let's keep "compilation unit" for old blog posts and for docs in `internals`. The compiler has CompilationUnits and SourceFiles and they are different. Misnaming them is bound to confuse.

So I'd keep only the changes under docs/reference and docs/usage.

2021-05-26 11:21 UTC, megri commented
> OK with the change for user-facing docs but let's keep "compilation unit" for old blog posts and for docs in `internals`. The compiler has CompilationUnits and SourceFiles and they are different. Misnaming them is bound to confuse.
> 
> So I'd keep only the changes under docs/reference and docs/usage.

Updated now

2021-06-14 14:41 UTC, merged