Interactive: fix `contextOfPath` for Template
lampepfl/dotty pull request #12783
Opened 2021-06-10 17:16 UTC by dos65

Without this fix, in case if input `path: List[Tree]` starts from `Template.constr` tree `contextOfPath` ignores parent trees and returns non-completed `Context` value.

2021-06-24 16:19 UTC, odersky requested changes
Logically, I'd expect to use `outer` if `constr` contains `nested` and `ctx` if `parents` or `self` contains `nested`. I might be wrong, but it's worth trying.

2021-07-08 12:52 UTC, bishabosha commented
Hi @dos65, will you be able to try out the change?

2021-07-08 12:59 UTC, dos65 commented
@bishabosha yes - will change it. Sorry, I forgot about this PR.

2021-07-16 15:23 UTC, dos65 commented
> Logically, I'd expect to use outer if constr contains nested and ctx if parents or self contains nested. I might be wrong, but it's worth trying.

@odersky 
I checked it one more time. For `constr`/`parents`/`self` it should return `outer`.  I added completion tests cases that is fixed by this change.

2022-02-08 10:06 UTC, dos65 commented
@odersky I rebased commit. Could we merge it?

2022-02-11 08:14 UTC, bishabosha approved these changes

2022-02-11 08:15 UTC, merged