change doc to recommend metals worksheet
lampepfl/dotty pull request #12874
Opened 2021-06-18 12:30 UTC by bishabosha

2021-06-18 13:14 UTC, smarter commented
Seems like we could just delete that page and point to the metals documentation which will always be more up to date

2021-06-18 15:04 UTC, tgodzik requested changes
@smarter might be right that Metals worksheet docs should be always more up to date. Is the current state of the docs enough though? https://scalameta.org/metals/docs/editors/vscode.html#worksheets

2021-06-18 15:04 UTC, tgodzik commented on docs/docs/usage/worksheet-mode.md
> +On top of the buffer, the message `Copy Worksheet Output` appears. Save the file to evaluate the code of the worksheet. Each line of output is printed on the right
I wouldn't mention `Copy Worksheet Output` here, it can be mentioned additionally.

2021-07-09 10:28 UTC, bishabosha commented
I will close do to the other rewrite being proposed by https://github.com/scala/docs.scala-lang/pull/2112

2021-07-09 10:28 UTC, closed without merging