Rewrite to no-indent keeps end comment
lampepfl/dotty pull request #12954
Opened 2021-06-27 01:54 UTC by som-snytt

```
class C:
  def f = 42
end C
```
is rewritten to
```
class C {
  def f = 42
} // end C
```
But of course no one would ever rewrite in that direction.

Also, offer a deprecation warning in the face of
```
class C:
end C
```
because it is misleading (colon means indented statements follow). Moreover, deleting the end marker results in bad syntax.

2021-07-01 15:49 UTC, dwijnand approved these changes
LGTM

2021-07-01 17:24 UTC, som-snytt commented
Deprecating "empty colonized template bodies" may be undesirable because accepting it was intentional; however, it is an excuse to use the phrase "empty colonized template bodies" outside a sci-fi context or academic paper.

2021-07-07 08:43 UTC, dwijnand commented
Could you propose that separately then?  Personally I don't like it, but I also don't like that `class C:` is bad syntax too - and changing _that_ would make your consistency point.

2021-07-07 08:43 UTC, dwijnand requested changes
^

2021-07-07 19:28 UTC, som-snytt commented
@dwijnand Rebased and kept only the feature described.

I'll propose deprecating empty body after colon separately; I don't feel strongly about it, except that "end marker is optional" strikes me as a useful rule that should not be violated lightly. (Note to self for later.)

Also dropped converting the converse, end comment to end marker, because it was just a heuristic that did not verify the identifier. Probably auto-end-marking is a more useful and consistent feature, for which there is a ticket; maybe the conversion can be done then.

2021-07-08 13:20 UTC, dwijnand approved these changes
LGTM, thanks Som

2021-07-08 13:20 UTC, merged

2023-04-28 09:35 UTC, adpi2 commented on compiler/src/dotty/tools/dotc/rewrites/Rewrites.scala
> +      }
I suspect this to be the root cause of https://github.com/lampepfl/dotty/issues/17187

```scala
object A:
    object B:
        def a = 2
```
When rewriting to no-indent, we want to add `  }\n` and then `}\n` at the exact same position. But this piece of code only keep the second patch, which leads to the incorrect:
```scala
object A {
    object B {
        def a = 2
}
```

2023-04-28 10:24 UTC, adpi2 commented
Tested also this:
```
class C:
  def f = 42

end C
```

And it is rewritten to this:
```
class C {
  def f = 42
}

end C
```

2023-04-28 10:41 UTC, som-snytt commented
@adpi2 it looks like it introduced "replace" semantics for "patch at a point". I don't remember now why. There is a tweak to "overlaps" to include overlaps if exactly one point.