ScalaDoc : type parameter in extension method is wrong
lampepfl/dotty pull request #13191
Opened 2021-07-28 15:56 UTC by KacperFKorban

fixes #12813

2021-07-29 21:05 UTC, pikinier20 approved these changes

2021-07-30 08:37 UTC, romanowski approved these changes

2021-07-30 09:29 UTC, bishabosha commented on scaladoc/src/dotty/tools/scaladoc/translators/ScalaSignatureUtils.scala
> +<<<<<<< HEAD
theres some merge conflict here

2021-07-30 09:31 UTC, bishabosha requested changes
it appears there is a merge conflict that was unresolved

2021-07-30 10:33 UTC, KacperFKorban commented on scaladoc/src/dotty/tools/scaladoc/translators/ScalaSignatureUtils.scala
> +<<<<<<< HEAD
fixed :sweat_smile:

2021-08-02 14:22 UTC, bishabosha approved these changes

2021-08-02 14:22 UTC, merged