Add TypeRepr.memberInfo, Symbol.tpe, Symbol.typeParams to reflection API
lampepfl/dotty pull request #13395
Opened 2021-08-26 14:15 UTC by pikinier20

2021-10-04 14:28 UTC, nicolasstucki commented
Part of #13371

2022-01-13 12:50 UTC, nicolasstucki requested changes
Each method should be added in one PR and include some tests

2022-01-13 12:50 UTC, nicolasstucki commented on compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala
> +        def tpe: TypeRepr = self.typeRef
This was in #9707

2022-04-25 09:19 UTC, pikinier20 commented
The problem was solved by #14892

2022-04-25 09:19 UTC, closed without merging