Add ClassDef.baseTypes to reflection API
lampepfl/dotty pull request #13398
Opened 2021-08-26 14:37 UTC by pikinier20

2022-01-13 09:50 UTC, nicolasstucki requested changes

2022-01-13 09:50 UTC, nicolasstucki commented on scaladoc/src/dotty/tools/scaladoc/tasty/ClassLikeSupport.scala
> +    // TODO use classDef.baseTypes
@pikinier20 SInce you created this PR the code below changed. Is this method still relevant or is `Symbol.baseCalsses` enough?

2022-01-13 09:50 UTC, nicolasstucki commented on tests/run-macros/baseTypes.check
> +List(scala.Some[Some.this.A], scala.Option[Some.this.A], java.io.Serializable, scala.Product, scala.Equals, scala.collection.IterableOnce[Some.this.A], java.lang.Object, scala.Matchable, scala.Any)
Adding this test I noticed that `baseTypes` is losing the type parameters. It might need to be implemented on `TypeRepr` directly.

2022-04-25 09:19 UTC, pikinier20 commented
The problem was solved by #14892

2022-04-25 09:19 UTC, closed without merging