Fix #13197: Handle AndType in widen
lampepfl/dotty pull request #13590
Opened 2021-09-22 18:08 UTC by noti0na1

Fix #13197 

The lhs of AndType could contain unknown variables.

2021-09-22 20:07 UTC, noti0na1 commented
This bug only happens when the function is inlined. 

@smarter Could you have a look of the code? I'm not sure whether this is the correct fix.

2021-09-23 11:17 UTC, smarter requested changes
I don't think `widen` should look inside types, this would be a big departure from its current behavior.
`(?1 : String | Null)` looks like a skolem and we have logic to widen skolem when ascribing a type to a val during typer: https://github.com/lampepfl/dotty/blob/aaac006a58c3f5d7fbd64d3a1a19261b51dfecf5/compiler/src/dotty/tools/dotc/typer/Namer.scala#L1707 It seems like the same logic should be used when we ascribe a type to a val during the inlining phase?

2021-09-23 17:44 UTC, noti0na1 commented
@smarter  This could also be a bug from named parameters.

```scala
extension [T](x: T | String) inline def forceString: x.type & String =
  x.asInstanceOf

trait Bar:
  def b: String | Int

class Foo(a: String = "", b: String)

object Foo:
  def foo(bar: Bar) = Foo(b = bar.b.forceString)
```

In typer, we can see the function `foo` becomes:

```scala
def foo(bar: Bar): Foo = {
  val b$1: (?1 : String | Int) & String = forceString[Int](bar.b)
  val a$1: String @uncheckedVariance = Foo.$lessinit$greater$default$1
  new Foo(a$1, b = b$1)
}
```

I think we need to widen the skolem type for `b$1` first?

2021-09-23 17:48 UTC, smarter commented
Yes that looks like the root of the problem indeed.

2021-09-24 09:08 UTC, smarter approved these changes

2021-09-24 09:08 UTC, merged