Add step by step example of how to use scaladoc
lampepfl/dotty pull request #13605
Opened 2021-09-24 10:53 UTC by kpodsiad

2021-09-27 07:37 UTC, kpodsiad commented
@pikinier20 IMO it would be nice to add an example of how to host docs using e.g. Github pages. Maybe there should be some repository where everything is configured and the user can see how it works & looks. What do you think?

2021-09-27 09:55 UTC, BarkingBad reviewed
Looks OK

2021-09-27 09:55 UTC, BarkingBad commented on docs/docs/usage/scaladoc/summary-example.md
> +  )
Wouldn't it be more convenient to not nest the settings

```suggestion
  Compile / doc / target := file("generated-docs"),
  Compile / doc / scalacOptions ++= Seq(
    "-project", "scaladoc example",
  )
```

2021-09-27 09:55 UTC, BarkingBad commented on docs/docs/usage/scaladoc/summary-example.md
> +However, so generated documentation is missing a single entry point.
Hopefully, this should be fixed in `3.1.0`. Can you add some tip note here?

2021-09-30 10:09 UTC, BarkingBad requested changes

2021-09-30 10:09 UTC, BarkingBad commented on docs/docs/usage/scaladoc/summary-example.md
> +However, in scaladoc `3.2.0` and earlier, so generated documentation is missing a single entry point. This is no longer case in `3.1.x` and hence `"-siteroot", "docs"` is not needed anymore.
```suggestion
However, in scaladoc `3.0.2` so generated documentation is missing a single entry point. This is no longer case in `3.1.x` and hence `"-siteroot", "docs"` is not needed anymore.
```

It was a regression brought by `-Yapi-subdirectory` flag introduced in `3.0.2`

2023-05-10 08:09 UTC, ckipp01 commented
Since there hasn't been any activity here in quite some time and much of this is contained in https://docs.scala-lang.org/scala3/guides/scaladoc/index.html, I'll go ahead and close this. If you feel like anything is still missing from the docs, feel free to port them.

2023-05-10 08:09 UTC, closed without merging