Add `reverse` method to `NonEmptyTuple`
lampepfl/dotty pull request #13752
Opened 2021-10-15 13:16 UTC by danicheg

In Scala 2, there is a method `swap` on `Tuple2`. In Scala 3, we could have it generalized version for any non-empty tuple as a whole.

2023-04-06 14:47 UTC, danicheg commented
If dotty's team is interested in taking this, I'm happy to move on with any changes :+1:

2023-05-10 08:06 UTC, ckipp01 commented
> If dotty's team is interested in taking this, I'm happy to move on with any changes 👍

@bishabosha since you were commenting on this I'll ping you. Is this something worth pushing forward? it looks like @Decel is willing if it is.

2023-05-11 10:47 UTC, bishabosha commented
I think its worth having, @Decel would you like to try a second attempt?

2023-05-11 11:45 UTC, bishabosha commented
> I think 2 is the best option available. But we need to come up with a design for the helper.

```scala
object Tuple:

  @experimental
  object Helpers:

    @experimental
    type ReverseImpl[Acc <: Tuple, X <: Tuple] <: Tuple = X match
      case x *: xs    => ReverseImpl[x *: Acc, xs]
      case EmptyTuple => Acc
```

2023-05-14 14:02 UTC, danicheg commented
fwiw: this definition of `Reverse` type doesn't work
```scala
type Reverse[X <: Tuple] <: Tuple = Helpers.ReverseImpl[EmptyTuple, X]
// ^ cannot combine bound and alias
```
Am I missing something?

2023-05-14 17:13 UTC, danicheg commented
I've addressed the review comments, thanks for your tips and suggestions. CI is green, so this could be reviewed once again.

2023-05-17 09:32 UTC, danicheg commented on library/src/scala/runtime/Tuples.scala
> +    if (xxl.productArity == 22) {
Yeah, indeed. Good call, thanks

2023-05-17 12:23 UTC, bishabosha commented
Experimental definitions shouldn't make warnings in mima so you can remove those changes

2023-05-17 12:56 UTC, danicheg commented
> Experimental definitions shouldn't make warnings in mima so you can remove those changes to MiMaFilters

Actually, I tried that locally before pushing it to the remote branch, and MiMa didn't like it.

2023-05-17 14:03 UTC, bishabosha commented
> Actually, I tried that locally before pushing it to the remote branch, and MiMa didn't like it.
I need someone else to advise here

2023-05-19 09:11 UTC, danicheg commented
If we don't mention anyone from the Scala3 team, this PR will get stuck as it was earlier. We all spent quite a lot of resources to get to this point, so can you @bishabosha @ckipp01 please step into finding the right person to perform a final push? But yeah, it's not an urgent thing at all.

2023-05-19 10:20 UTC, bishabosha commented
@Kordyjan what is the MiMa policy for experimental definitions?

2023-05-22 11:47 UTC, Kordyjan commented
They need to be listed in the MimaFilters. Everything looks good here!

2023-05-30 18:02 UTC, bishabosha commented
it can be released as experimental in a patch release

2023-06-03 11:49 UTC, danicheg commented
Good to know! So, I will do the final ping and stop bothering people with this.

2023-06-20 10:20 UTC, bishabosha commented on library/src/scala/Tuple.scala
> +  inline def reverse[This >: this.type <: Tuple]: Reverse[This] =
This method should also be moved to the `Tuple` trait, currently it is in `NonEmptyTuple`

2023-06-20 10:21 UTC, bishabosha commented on tests/run-custom-args/tasty-inspector/stdlibExperimentalDefinitions.scala
> +  "scala.NonEmptyTuple.reverse",
this will be affected when you move `reverse` to `Tuple`

2023-06-20 10:21 UTC, bishabosha commented on tests/run-deep-subtype/Tuple-reverse.scala
> +    println(Tuple1(1).reverse)
please add a test for `EmptyTuple.reverse`

2023-06-20 10:22 UTC, bishabosha requested changes
`reverse` should be a member of the `Tuple` trait to match its implementation

2023-07-02 13:29 UTC, danicheg commented
@bishabosha here we go (again)...

2023-07-02 13:38 UTC, bishabosha requested changes
Ok looks good, sorry could we also have a test that checks e.g. that `(1, true, "hello"). reverse` is typed as `(String, Boolean, Int)` and try to do a git rebase instead of pull - otherwise looks good

2023-07-02 16:20 UTC, danicheg commented
@bishabosha 
> could we also have a test that checks e.g. that (1, true, "hello"). reverse is typed as (String, Boolean, Int)

done
> try to do a git rebase instead of pull

could you accomplish a squash of commits when merging?

2023-07-03 14:03 UTC, merged