Tighten unary op syntax and untupling language
lampepfl/dotty pull request #14372
Opened 2022-01-28 01:24 UTC by som-snytt

Fixes #9241

Disallow unary ops with parens.

Follow up untupling spec where it is not pattern-matching like `.tupled`. It simply takes the params it knows to take.

2022-01-28 17:03 UTC, anatoliykmetyuk requested changes
Otherwise LGTM

2022-01-28 17:03 UTC, anatoliykmetyuk commented on docs/docs/reference/changed-features/operators.md
> +As a minor restriction, the first parameter list of a unary operator must not be explicit and empty.
```suggestion
A unary operator must not have explicit parameter lists even if they are empty.
```

2022-01-28 17:03 UTC, anatoliykmetyuk commented on docs/docs/reference/changed-features/operators.md
> +The reason for this restriction is that unary operator syntax does not support supplying an argument list, even if it is empty.
```suggestion
```

2022-01-28 17:04 UTC, anatoliykmetyuk commented on docs/docs/reference/changed-features/operators.md
> +The reason for this restriction is that unary operator syntax does not support supplying an argument list, even if it is empty.
I believe this one is redudant.

2022-01-28 18:17 UTC, som-snytt commented
It's not obvious to me that the reason I can't define
```
def unary_!() = false
```
is that I wouldn't be able to write prefix op syntax. What if I had no intention of using prefix op syntax? Perhaps my purpose was to sabotage prefix syntax for subclasses.

This is probably the only case where syntax restricts a regular language feature. For example, I can write extensions for `StringContext` that cannot be used as an interpolator.

2022-01-28 18:19 UTC, som-snytt commented
I used github's "commit suggestion" feature for the first time, but I see that it triggers tests.

2022-02-25 06:05 UTC, som-snytt commented
Rebased for conflicts, but accidentally lost review tweaks added via suggested edits.

Re-added tweaks per review.

2022-03-08 14:32 UTC, anatoliykmetyuk approved these changes

2022-03-08 14:32 UTC, merged