Fix: Weird Case Class Compiler Error with Inline Function #12508
lampepfl/dotty pull request #14476
Opened 2022-02-14 08:53 UTC by qiujiangkun

Revert `fix #11401 (proxy parameter should be owned by proxy)  (since boundSym is new, no need to use check in QuoteUtils.changeOwner)`

This reverts commit 02411504
This might help fix https://github.com/lampepfl/dotty/issues/12508

Seemingly fixes #12508, but I'm not sure what else it breaks. The new features are definitely missing

Proposed by

From: Nicolas Stucki <[nicolas.stucki@epfl.ch](mailto:nicolas.stucki@epfl.ch)>
Date: Mon, Jan 17, 2022 at 6:28 PM
Subject: Re: Building a tool on top of Dotty
To: Lionel Parreaux <[lionel.parreaux@gmail.com](mailto:lionel.parreaux@gmail.com)>
Cc: Martres Guillaume André Fradji <[guillaume.martres@epfl.ch](mailto:guillaume.martres@epfl.ch)>

A quick fix might be to revert https://github.com/lampepfl/dotty/commit/024115044424406b4cce1529dbd1236c1ab26b20 and publish it locally. 

On Mon, 17 Jan 2022 at 02:47, Lionel Parreaux <[lionel.parreaux@gmail.com](mailto:lionel.parreaux@gmail.com)> wrote:

Salut Nico, (Cc Guillaume),

Un étudiant à moi essaie de construire une nouvelle approche pour spécialiser les programmes polymorphes, et on a décidé d'utiliser Dotty/Scala 3 comme base pour notre implémentation.

Malheureusement, on n'arrive pas à définir des classes polymorphes (crucial pour le projet) dans des macros à cause de Weird Case Class Compiler Error with Inline Function · Issue #12508 · lampepfl/dotty (github.com)
Donc on a essayé d'utiliser le Tasty Reader à la place, mais on se heurte maintenant à 

Y a-t-il un moyen simple de contourner ces problèmes ? Ou une idée pour les résoudre directement dans le compilateur ?

Merci d'avance pour les conseils.

— LP

2022-02-14 14:31 UTC, nicolasstucki commented on tests/pos-macros/i11401/Main_2.scala
> -package i11401
This test should not be deleted

2022-02-14 14:33 UTC, nicolasstucki requested changes
This PR should introduce a tests for the feature being fixed

2022-02-14 14:37 UTC, nicolasstucki commented
Revering this introduces more bugs. In the email, it was proposed as a quick workaround.

2023-05-10 08:07 UTC, qiujiangkun commented
Sorry. I'm more busy than ever. Almost forgot about context

2023-05-10 08:17 UTC, closed without merging