check if package names will be encoded in desugar
lampepfl/dotty pull request #14597
Opened 2022-03-01 16:12 UTC by bishabosha

produce a warning if they are - this is because encoding a package name is mostly undefined behaviour that the scala 3 compiler magically recovers from - but could be problematic.

fixes #14448

2022-03-01 16:12 UTC, bishabosha commented
test performance please

2022-03-01 16:35 UTC, sjrd requested changes

2022-03-01 16:35 UTC, sjrd commented on compiler/src/dotty/tools/dotc/util/Chars.scala
> +         '|' | '/' | '\\' => true
`isJavaIdentifierPart` returns `false` for all those characters. So you can remove this.

2022-03-02 10:42 UTC, sjrd approved these changes

2022-03-07 15:01 UTC, merged