Add source 3.2 language version
lampepfl/dotty pull request #14629
Opened 2022-03-07 12:21 UTC by bishabosha

make it more simple to introduce new language versions that enable no extra features (such as `3.1`).

Sets default language mode to `3.2`.

If we enable some features from `future` by default, then we should revert 88ed2052fad320a44acbf1fbd79867e2671d3dd7

2022-03-07 12:32 UTC, bishabosha commented
Ideally language.`3.1-migration` would not have been added to the library, which could simplify the design of mapping from imports to real source versions - now we are basically making it a rule that each minor version should have a "migration" import, even it is a no-op

2022-03-07 13:05 UTC, smarter commented
Let's hold off on this until today's meeting to decide whether we're actually releasing 3.2.0-RC1 or 3.1.3-RC1 this week.

2022-03-07 13:43 UTC, michelou commented
@smarter +1 for 3.1.3-RC1.

2022-03-07 14:28 UTC, odersky requested changes
I am not sure about the `series` concept. That adds another complication to it which is invisible from the version numbers. 

I'd recommend to just add the new version number for now, without changing the infrastructure. Make a separate PR if we still think there should be a series concept after discussing it.

2022-03-15 15:01 UTC, bishabosha commented
rebased after https://github.com/lampepfl/dotty/pull/14690 was merged

2022-03-15 15:21 UTC, bishabosha commented
@odersky this PR now introduces the series concept without modifying the library, `3.2` is treated the same as `3.0`, `3.1`.

2022-04-04 14:18 UTC, bishabosha commented
we should instead deprecate the `scala.language.3.1-migration` object and make it an error to import (e.g. check that there is a corresponding option in the `-source` flag

2022-04-04 14:19 UTC, closed without merging