Cache skolem types
lampepfl/dotty pull request #14909
Opened 2022-04-12 09:43 UTC by odersky

Skolem types were not cached, which means that any type containing a skolem type
was not cached either. This meant that the same match type with a skolem type as
selector was created many times instead of once, so its reduction was not cached
either. We now cache skolem types. It's a bet that in practice few skolem types are
created and that therefore the hashtable pollution with skolemtypes is less of
a problem than the potential problem of losing identity of types containing
skolem types.

Fixes #14903

2022-04-20 20:20 UTC, smarter requested changes
I've opened https://github.com/lampepfl/dotty/pull/14987 as an alternative to this PR which fixes the performance issue without requiring skolems to be cached.

2022-04-26 09:22 UTC, odersky commented on compiler/src/dotty/tools/dotc/core/Types.scala
> +    override def computeHash(bs: Binders): Int = identityHash(bs)
No, a skolem is in any case unique. We never merge two skolems. So it does not matter whether we 
cache the info or not.

2022-04-26 09:34 UTC, odersky commented on tests/pos/i14903.scala
> +trait Wrapper[T] {
I think we can argue by analogy to type variables. Both skolem types and type variables are locally generated, and both are usually part of more complicated types. Type variables are cached, so it makes sense to cache skolem types as well.

2022-04-26 13:44 UTC, smarter commented on tests/pos/i14903.scala
> +trait Wrapper[T] {
OK, I've edited the commit message to mention this and dropped the duplicate test.

2022-04-26 13:44 UTC, smarter approved these changes

2022-04-26 16:19 UTC, merged