Setup integration with the unmanaged community build
lampepfl/dotty pull request #14920
Opened 2022-04-13 09:30 UTC by WojciechMazur

This PR sets up integration with the [unmanaged community build](https://scala3.westeurope.cloudapp.azure.com/) by triggering the run with the latest nightly version of Scala

Before merging secret `BUILD_TOKEN` should be set for the Dotty repo based on the secure token set in the Jenkins instance of the unmanaged community build.

The unmanaged community build is not restricted to the list of maintained projects within dotty-staging and can run most of the OSS projects based on information fetched from Scaladex and Maven. Instead of maintaining forks of the projects and using them in the managed community build, we do build the projects using the last release tag. It supports handling dependencies between the builds - project builds are aware of both their upstream and downstream builds, which allows waiting until dependencies are being built and published to the custom Maven repository shared within the build. It supports both sbt and mill (limited) builds. The projects used for the build are picked by their popularity measured in GitHub stars.
The sources of the unmanaged community build can be found here: https://github.com/VirtusLab/community-build3

2022-04-13 20:04 UTC, romanowski commented
cc @SethTisue

2022-04-13 21:16 UTC, SethTisue commented
cool!

2022-04-14 13:05 UTC, anatoliykmetyuk requested changes
I would propose to make this a separate job that depends on `publish_nightly`. `nightly_documentation` depends on `publish_nightly`, so, if the script in this PR fails, the documentation won't be published although it should.

2022-04-26 10:58 UTC, anatoliykmetyuk approved these changes

2022-04-26 10:59 UTC, merged