Aligns `| Nothing` with `& Any` and `Nothing |` with `Any &` for value types
lampepfl/dotty pull request #14971
Opened 2022-04-19 14:15 UTC by nicolasstucki

Aligns `| Nothing` with `& Any` and `Nothing |` with `Any &` for value types.

This also fixes `summon[ClassTag[Int | Nothing]]` as it is now equivalent to `summon[ClassTag[Int]]`.

Fixes #14970
Fixes #14964

> :warning: This is a binary breaking change.

> the Previous version generated the `def f: Int` and `def f: Object` variants of the method.
> In the new one, we only generate the `def f: Int` version.
> Unfortunately, the previous version called the boxed version of the interface that does not exist anymore.
>
> Is this something that we encounter in practice?

2022-04-20 06:33 UTC, nicolasstucki commented
As far as I can see, the `Int | Nothing` pattern should not appear in any user code. If this is the case then changing it should not impact signatures in real code. It will impact the `ClassTag` by fixing cases that were buggy.

I would argue that this erasure is a bug and should be fixed. If a library accidentally used this and cares about binary compatibility, they can add the bridge themselves.

2022-04-20 07:31 UTC, sjrd commented
> they can add the bridge themselves.

I don't think that's possible. How would they do that? It would result in an ambiguous overload, wouldn't it?

2022-04-20 08:59 UTC, nicolasstucki commented
>> they can add the bridge themselves.

> I don't think that's possible. How would they do that? It would result in an ambiguous overload, wouldn't it?

Indeed 😞

2022-04-20 22:57 UTC, smarter commented
You can avoid ambiguous overload errors by relying on `@targetName`:
```scala
import scala.annotation.targetName
class A:
  def foo: Int = 1
  @targetName("foo") def fooBinCompat: Any = 1
```

2022-04-20 23:00 UTC, smarter commented
... but that's not good enough for library authors in general as a workaround to binary compatibility breakages, because their methods might be overrridden in user code as @sjrd pointed out last time I wanted to break binary compatibility :grimacing:

2022-04-21 07:28 UTC, nicolasstucki commented
Then the real question is if there are libraries that use these types in their signatures.

2022-04-21 10:43 UTC, odersky commented on compiler/src/dotty/tools/dotc/core/TypeErasure.scala
>      // After erasure, C | {Null, Nothing} is just C, if C is a reference type.
I think this logic has gotten a bit messy and can be simplified. Why not:
```scala
if tp1.isRef(defn.NothingClass)
    || tp1.isRef(defn.NullClass) && tp2.derivesFrom(defn.ObjectClass))
then return tp2
```
And the same for `tp1`.

2022-04-21 10:46 UTC, odersky requested changes
I would hope that A | Nothing would not normally appear in library code. The current behavior looks wrong since it violates the property that `erasure(A | B) = erasure(B)` if `A <: B`.

So I'd tend to go ahead with merging this after the logic is made clearer.

2022-04-21 12:06 UTC, smarter commented
> You can avoid ambiguous overload errors by relying on @targetName:

By the way, even if this works around (some) binary-compatibility issues, it can also break tasty-compatibility since we refer to methods by their original names there.

2022-04-21 12:19 UTC, nicolasstucki commented
> The current behavior looks wrong since it violates the property that `erasure(A | B) = erasure(B) if A <: B`

I believe it is not violated. With the current behavior, `Int | Nothing` and `Nothing | Int` erase to `Int`.
* `erasure(Int | Nothing) = erasure(Nothing) if Int <: Nothing` the guard does not hold
* `erasure(Nothing | Int) = erasure(Int) if Nothing <: Int` the guard holds and we have the correct erasure

Similarly for `erasure(A | B) = erasure(A) if B <: A`.

2022-04-21 12:45 UTC, nicolasstucki commented
Apart from signatures and `ClassTag`s is there something else that uses erased lub?

2022-04-21 13:21 UTC, nicolasstucki commented on tests/run/i14964b.scala
> +  println(summon[reflect.ClassTag[Int | Nothing]]) // classOf[Object]
```suggestion
  println(summon[reflect.ClassTag[Int | Nothing]]) // classOf[Int]
```

2022-04-21 14:00 UTC, dwijnand approved these changes
LGTM

2022-04-21 14:03 UTC, nicolasstucki commented
Based on #14998, the only `Nothing | T` `erasedLub` is for `Nothing | Null` which used to erase to `Object` and still erases to `Object`.

2022-04-21 16:08 UTC, smarter commented
Breaking binary compatbility likes this sets a bad precedent. Is the current behavior really fundamentally broken or merely inconvenient?

2022-04-21 16:17 UTC, nicolasstucki commented
> Breaking binary compatbility likes this sets a bad precedent. Is the current behavior really fundamentally broken or merely inconvenient?



As far as I can see it is only fundamentally broken for the `ClassTag` use case. It seems that the signature side only causes unnecessary boxing. I will investigate further to see if I can find a situation where the signatures break something.

We could do an alternative fix for #14964 that would make the erased lub behave differently if we are computing the erased type for a `ClassTag`.

2022-04-21 16:38 UTC, smarter commented
Actually you don't even need ClassTag to run into issues:
```scala
object Test {
  def main(args: Array[String]): Unit = {
    val x: Array[Int | Nothing] = Array()
    val y: Array[Int] = x
  }
}
```
```scala
Exception in thread "main" java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [I
        at Test$.main(arri.scala:3)
        at Test.main(arri.scala)
```
So yeah, I guess the erasure of union types is just fundamentally broken which would justify changing it :/. If we do change it in 3.2, we could warn in 3.1.3 about any code that relies on it to ease migration.

2022-05-02 17:28 UTC, odersky approved these changes
LGTM

2022-05-04 10:11 UTC, merged

2022-05-04 10:28 UTC, bishabosha commented
this will also break backwards tasty compatibility of resolving methods by their signature