Disallow old uses of quoted and spliced types
lampepfl/dotty pull request #15012
Opened 2022-04-22 13:48 UTC by nicolasstucki

These have have been emitting migration warning in 3.0 and 3.1 even if the
syntax was already deprecated in 3.0. These where allowed syntax found
in older papers.

The case `'[T]` was actually buggy but no one reported this bug so far.
A good indication that this older syntax has not been used in a while.

First step towards fixing #15009.

2022-04-25 14:55 UTC, odersky requested changes
1. If we change this, we need to change `syntax.md` (both versions) as well.

2. Currently, in syntax.md I find
     ```
     paren            ::=  ‘(’ | ‘)’ | ‘[’ | ‘]’ | ‘{’ | ‘}’ | ‘'(’ | ‘'[’ | ‘'{’
     ```
    That's wrong. isn't it? `'{` and friends are two tokens, or not? In that case we need to change this part as well.

 3. I am not sure what the motivation for the change is. If we do use 
     ```
     `[ ... ]
     ```
    in patterns, would it not be more general to allow it in types as well?

2022-04-28 13:15 UTC, nicolasstucki commented
> I am not sure what the motivation for the change is. 

We do not really change anything in this PR, we are just disallowing the use of syntax that was already deprecated in 3.0.0. This allows us to check the use of this syntax directly into the parser. This refactor makes `untpd.TypSplice` unnecessary.

2022-05-19 12:43 UTC, nicolasstucki commented
rebased

2022-05-23 17:57 UTC, odersky approved these changes

2022-05-24 08:36 UTC, bishabosha commented
needs another rebase

2022-05-24 12:05 UTC, merged