Local classes are uncheckable (type tests)
lampepfl/dotty pull request #15134
Opened 2022-05-06 17:46 UTC by dwijnand

2022-05-09 10:52 UTC, dwijnand commented
I didn't look into the detail, but it looks like doing it so bluntly breaks:

```
 - dotty.communitybuild.CommunityBuildTestB.http4s
 - dotty.communitybuild.CommunityBuildTestB.scodec
 - dotty.communitybuild.CommunityBuildTestB.fs2
```

2022-05-11 12:42 UTC, dwijnand commented
@smarter maybe you're interested to review this, seeing as it's an old one you created.

2022-05-11 13:07 UTC, smarter commented
No time to review this unfortunately, but traversing all types of all declarations of all base classes could be pretty expensive.

2022-05-11 13:28 UTC, dwijnand commented
It's all types of all declarations of all base classes defined in the method, is hopefully ok.  And I'm all ears for whether there's a better way to do it.

2022-05-26 11:36 UTC, odersky requested changes
I also think we should keep searching for a more efficient way to fix this. But I don't have the time right now to do it. So it's probably best to revisit this later.

2022-05-28 21:09 UTC, smarter commented
Maybe we should consider all type tests to local classes as unchecked by default, the one case which is safe is when we go from one local class to another local class defined in the same scope:
```scala
def foo = {
  sealed trait A
  class B extends A
  val x: A = new B
  x match { case x: B => x }
}
```
Anything else could end up giving you an instance of a local class coming from a different call to the same method which semantically is a different class.

2022-05-28 21:16 UTC, smarter commented
In other words the check would be something like "`(x: A).isinstanceOf[B]` emits a warning if `B` is a local class which is not statically reachable from the scope where `A` is defined"

2022-05-29 10:58 UTC, dwijnand commented
> Anything else could end up giving you an instance of a local class coming from a different call to the same method which semantically is a different class.

That seems overly strict.  A local class that doesn't depend on anything in the method surely isn't "unchecked" when used, such as:

```scala
class A
def foo = {
  class B extends A
  val x: A = new B
  x match {
    case x: B =>
    case _ =>
  }
}
```

But I did realise from your comment that I'm not considering singleton types based on any terms in the method, like any parameters.

Going back to performance, the check here sounds big, but it's "only" on the types of the declarations in the local classes.  So if you have a local class with 30 methods, or 10 local classes with 3 methods, it will take the time that takes.  But I think it's fairly limited, as local classes tend to be few and small, in my experience.  In the case of fs2, https://github.com/dotty-staging/fs2/blob/main/core/shared/src/main/scala/fs2/Pull.scala#L824-L1260 I think I counted 8 classes with about 5 methods each, which seems excessive to me.  I'm also not caching this information anywhere, admittingly, so I could look into that if desired.

2022-05-29 11:05 UTC, smarter commented
Your example matches the exception to the unchecked warning I gave above.

2022-05-30 12:10 UTC, dwijnand commented
Oh.  Then how are you defining "statically reachable", because I'd assumed being defined in a def disqualified it.

2022-05-30 12:17 UTC, smarter commented
I meant reachable through only static references from a specific scope (which might be the scope of a def)

2022-05-30 12:23 UTC, smarter commented
Oh but actually I misread your example, i didn't see that A was defined outside the def and B inside. Then I assert that we should get an unchecked warning: in general you cannot know if the B you get was created in the current call to the def or in a different call and escaped, and in the latter case it's really a different class B that happens to have the same runtime representation

2022-05-30 12:37 UTC, dwijnand commented
Right.  Do we have some verbiage to back up that claim?  Because I think many users consider the fact that classes can be defined locally to be a proximity convenience rather than also implying method-call uniqueness in those class types.  I find it particularly hard to defend that claim because it's impossible to build a true neg test for that match, using my class definitions.

2022-06-12 15:47 UTC, odersky commented
Note: `classSymbols` is not the same as `baseClasses`.

2022-06-12 15:51 UTC, smarter commented
> classSymbols of Foo | Bar is {Foo, Bar}.

Is it? `classSymbols` calls `parentSymbols` which does https://github.com/lampepfl/dotty/blob/0260d758d89d01ab445c471aa159ca8367d596ba/compiler/src/dotty/tools/dotc/core/Types.scala#L539-L540
(not sure what the spec in question is)

2022-06-12 16:06 UTC, odersky commented
Ah sorry, I meant `Bar & Foo`. For `Bar | Foo`, classSymbols is empty. But in any case it has nothing to do with baseClasses.

2022-06-12 20:36 UTC, dwijnand commented
Right, sorry, parentSymbols, not baseClasses.

2022-07-05 16:00 UTC, odersky reviewed
Otherwise LGTM

2022-07-05 17:32 UTC, dwijnand commented on compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala
> -        case AnnotatedType(_, annot) if annot.symbol == defn.UncheckedAnnot =>
Ah, I see that now: the previous behaviour mapped `T @foo @unchecked @bar` to `? @bar` while my diff made it map to `?`, but at the quadratic cost of each annotation when there isn't an `@unchecked`.  I'll revert.

2022-07-05 17:34 UTC, dwijnand commented on compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala
> +    val res = X.widenTermRefExpr.hasAnnotation(defn.UncheckedAnnot) || recur(X.widen, replaceP(P))
This is for whether the scrutinee was annotated `@unchecked`:

```scala
  def test8[T](x: T): T =
    class A(val elem: T)
    val p = prev
    (p: @unchecked) match
      case prev: A => prev.elem
      case _       => prev = new A(x); x
```

2022-07-05 17:36 UTC, dwijnand commented
Let me know if you're happy with my answer (assuming, as I do, that CI passes).

2022-07-06 16:52 UTC, odersky approved these changes
Yes, looks all good to me now,

2022-07-06 16:52 UTC, merged