Allow for unqualified `apply` as context functions
lampepfl/dotty pull request #15417
Opened 2022-06-10 16:42 UTC by odersky

Fixes #15414

2022-06-10 16:50 UTC, smarter requested changes

2022-06-10 16:50 UTC, smarter commented on compiler/src/dotty/tools/dotc/typer/Typer.scala
> +        case Ident(nme.apply) => This(tree.symbol.owner.asClass).withSpan(tree.span)
I think this doesn't handle unqualifed `apply` that are resolved by an import:
```scala
object X { class C(); object C; object D { import C.*, apply() } }
```
More robust:
```suggestion
        case tree @ Ident(nme.apply) => tpd.desugarIdentPrefix(tree)
```
```

2022-06-10 16:54 UTC, odersky commented
@smarter Yes, good suggestion.

2022-06-10 16:56 UTC, smarter commented
Actually even better would be to use tpd.qualifier to handle the match: https://github.com/lampepfl/dotty/blob/9614fb9ce148e184d40948060904d0b1bd713ec0/compiler/src/dotty/tools/dotc/ast/TreeInfo.scala#L854-L861

2022-06-10 17:26 UTC, smarter approved these changes

2022-06-11 08:44 UTC, odersky commented
We now don't allow single apply's to be used as constructor proxies

The previous commits allowed them but that caused runtime errors in Specs2 since
`apply` was bound to something different from before.

Since this is a weird corner case it's better not to allow it. As long as we do
not crash we are good.

The error message we get now is:

    constructor proxy `apply` cannot be used as a value

which is also a bit strange, but since this is a truly weird corner case it's not worth it
to finetune this.

2022-06-11 08:45 UTC, smarter approved these changes

2022-06-11 15:42 UTC, merged