Remove obsolete note on escapes in interpolations
lampepfl/dotty pull request #15450
Opened 2022-06-15 08:22 UTC by som-snytt

Scala 2/3 have parity on "how to escape double quote in an interpolated string with single-double quotes" since https://github.com/lampepfl/dotty/pull/11751

This commit deletes the "changed feature" note that was added pre-pandemic in https://github.com/lampepfl/dotty/pull/7486

To summarize, or recollect, `s"$"hi$""` is interpolator-agnostic. `s"\"hi\""` supplies the escapes to the interpolator by not taking `\"` as end-of-string. The standard interpolator understands `\"` as literal quote.

There is no provision for `s"text\"`, which is unclosed.

2022-09-04 17:43 UTC, som-snytt commented
@pikinier20 is this a no-brainer? I haven't followed whether there are changes in how docs are handled in scala 3.

2022-10-31 19:24 UTC, SethTisue commented
@Sporarum is this one you'd be interesting in reopening and reviewing?

2022-11-28 12:37 UTC, Sporarum commented
@som-snytt I'm not very familiar with these escaping questions, could you clarify what you mean by

> `s"$"hi$""` is interpolator-agnostic. `s"\"hi\""` supplies the escapes to the interpolator by not taking `\"` as end-of-string. The standard interpolator understands `\"` as literal quote.

2022-11-28 16:37 UTC, som-snytt commented
```
scala 2.13.10> s"$""
val res0: String = "

scala 2.13.10> s"\""
val res1: String = "

scala 2.13.10> raw"\""
val res2: String = \"
```

2022-11-29 10:26 UTC, Sporarum commented
And from my tests, the behaviour is the same in Scala 3.2.0
So the point of this PR is to say there is no more a difference between 2 and 3, got it

Now the question, why was this PR closed ?

2022-11-29 10:38 UTC, som-snytt commented
"Closed for inactivity."

2022-12-02 09:29 UTC, Sporarum commented
Oh I see, I believe this would be valuable
I think it is not mergeable as-is, because we wish to keep the links valid

I see two options:
* Delete the page during a version change, assuming we do not guarantee the stability of pages at urls like https://docs.scala-lang.org/scala3/reference/syntax.html but we do for url including a version number, like https://dotty.epfl.ch/3.0.0/docs/reference/syntax.html
* Updating the page to say it no longer applies

2023-01-04 23:02 UTC, som-snytt commented
@Sporarum I updated the page per your second suggestion, but I made it interesting instead of boring. It's worth advertising the behavior anyway.

Also TIL "Quentin Bernet". Is a bernet the sort of beret they wear in Berne?

2023-01-04 23:12 UTC, som-snytt commented
I don't know if that is 99% by weight or volume.

2023-01-05 13:00 UTC, Sporarum approved these changes
Looks good to me !

(I'm not 100% sure of the etymology of my name, but it seems indeed linked with the city of Bern, it might mean "from Bern" or something like that)

2023-01-05 13:04 UTC, Sporarum reviewed
Oh actually, we should maybe keep a part that explicitly mentions the old Scala 3 behaviour, again for the link's sake ?

2023-01-05 13:07 UTC, Sporarum requested changes
Upon further consideration, I think the `raw` example should be included before this gets merged, to motivate the existence of the feature, and it's difference with the other way

2023-02-02 19:13 UTC, som-snytt commented
Closing again because you're merging https://github.com/lampepfl/dotty/pull/16772 instead. Show some respect.

2023-02-02 19:13 UTC, closed without merging

2023-02-02 20:06 UTC, SethTisue commented
@som-snytt can't tell if you're in earnest or not?

I see some overlap between the two PRs, but not _all_ that much.

2023-02-02 20:14 UTC, som-snytt commented
My point is that rebasing stale PRs is rock bottom contributor experience. "Use it or lose it."

2023-05-24 06:12 UTC, som-snytt commented
This would have been an appropriate section, perhaps, to document https://github.com/scala/bug/issues/12789 rooted `StringContext`.