Fix `throwReturn` of `NonLocalReturns` to allow wider usage
lampepfl/dotty pull request #15495
Opened 2022-06-22 01:26 UTC by soronpo

See https://contributors.scala-lang.org/t/scala-nonlocalreturns-ergonomics-are-problematic/5767

2022-06-22 07:51 UTC, sjrd requested changes
LGTM, other than the whitespace comments below.

2022-06-22 07:51 UTC, sjrd commented on tests/run/nonlocal-return.scala
> +
Spurious blank line here.

2022-06-26 07:43 UTC, soronpo commented on tests/run/nonlocal-return.scala
> +  def animal(arg : Int) : Animal = returning {
fixed

2022-06-26 07:43 UTC, soronpo commented on tests/run/nonlocal-return.scala
> +
fixed

2022-06-26 07:56 UTC, sjrd approved these changes

2022-06-26 09:06 UTC, merged