Fix PlainPrinter.scala: Incorrect type parameters
lampepfl/dotty pull request #15899
Opened 2022-08-24 09:36 UTC by Sporarum

What it prints might be counter intuitive at first, but is correct
The clearest example is in i5345, where otherwise the printed output
doesn't correspond to the declaration

This is a requirement for Clause Interleaving #14019

2022-08-29 07:52 UTC, rochala approved these changes

2022-08-29 07:59 UTC, dwijnand requested changes
I agree that

```diff
-def x[A, B] => Conversion[A, B]
+def x[A, B]: Conversion[A, B]
```

is better.

But every other one is wrong, IMO.

2022-08-29 08:43 UTC, Sporarum commented
> I agree that
> 
> ```diff
> -def x[A, B] => Conversion[A, B]
> +def x[A, B]: Conversion[A, B]
> ```
> 
> is better.
> 
> But every other one is wrong, IMO.

https://github.com/lampepfl/dotty/pull/15899/files#diff-6a1575ea6525fe8c1a48627498a492b4e9c3ce82b78fb8b0f2a68cea8e6d339dR643-R646
Why should the completion be different than the declaration ?

This is not the case as long as there are normal parameters, for example:
https://github.com/lampepfl/dotty/pull/15899/files#diff-6a1575ea6525fe8c1a48627498a492b4e9c3ce82b78fb8b0f2a68cea8e6d339dR650-R653

We're just less used to see methods like `def res[T]: T`, so it feels a bit weird

2022-08-29 08:50 UTC, Sporarum commented
I think there is a case to be made for the errors, but then again, I think the problem is more general:
https://github.com/lampepfl/dotty/blob/cfbca8c660c21edeb3a6a83e8fe736ea9f6dd1c1/tests/neg-custom-args/fatal-warnings/i9408a.check#L8

2022-08-29 11:45 UTC, julienrf commented
I agree with @Sporarum, the changes he proposes are more consistent. The current implementation produces “signatures” that don’t match their corresponding definitions. With this PR, the printed signatures do match the definition syntax, and they will also work with interleaved types/terms parameter clauses.

2022-08-30 08:40 UTC, dwijnand approved these changes
Ah, I see now.  I thought it was printing types, not signatures.

2022-08-30 08:58 UTC, merged