Exclude match aliases from partial unification attempts
lampepfl/dotty pull request #15996
Opened 2022-09-08 09:15 UTC by odersky

Fixes #15983

2022-09-08 16:33 UTC, smarter commented
I don't understand what's specific about aliases to match types here, surely we should still be able to construct type lambdas involving them?

2022-09-08 16:55 UTC, odersky commented
Well, no, it crashes in the partial unification code otherwise.

2022-09-08 16:56 UTC, odersky commented
I think we require that a match type alias is always fully applied.

2022-09-08 17:01 UTC, smarter commented
> I think we require that a match type alias is always fully applied.

This doesn't seem to be required in sources, using the same TupleUnionLub match type from the test case I can write:
```scala
class Foo[F[_]]
val x = new Foo[[X] =>> TupleUnionLub[Tuple, Any, X]]
```
I would expect partial unification to generate type lambdas like this too.

2022-09-08 20:37 UTC, odersky commented
OK, so do you want to take a look at it?

2022-09-08 21:44 UTC, smarter commented
I'll assign myself to the issue.

2022-10-09 10:58 UTC, odersky commented
Issue has been open for a month now.

2022-10-09 11:22 UTC, smarter commented
I did not have a job during that month.

2022-10-12 19:21 UTC, smarter requested changes
I was able to minimize the original issue to not involve match aliases and still crash (with or without the change in this PR): https://github.com/lampepfl/dotty/issues/15983#issuecomment-1276633338
I'll start working on a fix now.

2022-10-16 10:40 UTC, closed without merging