Split out immutable GadtConstraint
lampepfl/dotty pull request #16602
Opened 2022-12-30 17:58 UTC by dwijnand

2023-01-24 00:48 UTC, Linyxus requested changes
Otherwise LGTM! 👍

2023-01-24 00:48 UTC, Linyxus commented on compiler/src/dotty/tools/dotc/core/GadtConstraint.scala
> +  private def gadt_=(g: GadtConstraint) = myGadt = g
Maybe we should not make `GadtConstraint` a private variable in `GadtConstraintHandling`, but declare two methods for retrieving and updating GADT constraints in this trait, and require the class that extends this trait to provide this two methods, just like what we do in `ConstraintHandling` ([here](https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/core/ConstraintHandling.scala#L36-L37)). Then `Context.fresh` would do the job of `GadtConstraint.fresh` as long as we put the `GadtConstraint` in the context.

2023-01-24 22:14 UTC, dwijnand commented
> Shall we have a `GadtConstraint` in the `Context` and extends `GadtConstraintHandling` wherever we would like to manipulate GADT constraints?
>
> Maybe we should not make `GadtConstraint` a private variable in `GadtConstraintHandling`, but declare two methods for retrieving and updating GADT constraints in this trait, and require the class that extends this trait to provide this two methods, just like what we do in `ConstraintHandling` ([here](https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/core/ConstraintHandling.scala?rgh-link-date=2023-01-24T00%3A48%3A58Z#L36-L37)). Then `GadtConstraintHandling` will be a stateless mixin for GADT constraint manipulation, and `Context.fresh` would do the job of `GadtConstraint.fresh` as long as we put the `GadtConstraint` in the context.

So that doesn't work, because we want code that's running in an inner context to have changes apply to an outer context. 
 It's similar to TyperState.   To that end I renamed it to GadtState, which is shorter and more palatable.

2023-01-26 01:45 UTC, Linyxus approved these changes
Thanks for the explanation. LGTM!

2023-01-26 01:47 UTC, merged