Fix #16405 - wildcards prematurely resolving to Nothing
lampepfl/dotty pull request #16625
Opened 2023-01-05 23:29 UTC by jchyb

Fixes #16405, which was a problem because it could it get in the way of some metaprogramming techniques. The main issue was the fact that when typing functions, the type inference would first look at the types from the source method (in `decomposeProtoFunction` resolving found type wildcards to `Nothing`) and only after that, it could look at the target method.
Now, in the case of wildcards we delay the resolution from the source method until later, after which it is resolved according to the target method (in `inferredFromTarget`). We also modify the target type resolution method (`inferredFromTarget`) a bit, as just applying the above procedure would fail some of the tests, eg.

val y1: Function1[_, Nothing] = x => x

would be typed as Function1[Any, Nothing], which was incorrect.

On a side note I will fully admit that that setting the minimizeSelected option for `isFullyDefined` inside of `inferredFromTarget` was a bit of an experiment on my part, nevertheless this seems to instantly work well with all of the test cases. An alternative would be to allow `decomposeProtoFunction` to proceed as before, and check if `formal` type was resolved to `Nothing` in `inferredFromTarget` and handle things that way, but that brings with itself its own set of issues (that I hope to avoid here).

2023-01-06 00:57 UTC, jchyb commented
Never mind, forgot about the bootstrapped only tests, I'll look into this tomorrow

2023-01-11 09:31 UTC, jchyb commented
Changed approach due to the above one failing the tests.
Now we check for wildcards in `decomposeProtoFunction`, and if detected we change order in what we use to try to infer types (to simplify: by default first we try protoFormal, then to infer from target, however with wildcard we try first to infer from target and only then `protoFormal`).

2023-01-23 15:40 UTC, odersky commented
It looks a bit heavyweight for what it achieves, but I am not yet sure whether one can do better. I'll take a closer look.

2023-01-24 14:55 UTC, odersky commented
@jchyb Can you push it to staging please? That makes it easier for me to work with it.

2023-01-24 15:18 UTC, jchyb commented
Done: https://github.com/dotty-staging/dotty/tree/fix-i16405
Should I reopen this PR with the different source?

2023-01-25 08:38 UTC, odersky requested changes
The approach is correct, but I think it can be simplified.

2023-01-25 08:38 UTC, odersky commented on compiler/src/dotty/tools/dotc/typer/Typer.scala
> +  private def decomposeProtoFunction(pt: Type, defaultArity: Int, pos: SrcPos)(using Context): (List[Type], Option[List[Boolean]], untpd.Tree) = {
I think I found another way that achieves the same outcome and that does not need a separate list of booleans.

2023-01-25 08:38 UTC, odersky commented on compiler/src/dotty/tools/dotc/typer/Typer.scala
> +            case bounds @ TypeBounds(nt, at) if nt == defn.NothingType && at == defn.AnyType => true
Type comparison via `==` or `!=` is not recommended. One can compare types with `eq`, or pattern match the structure and compare symbols. Or else use `=:=` which is semantic equality, equivalent to mutual subtyping, but this one is expensive. 

In this specific case, there are detectors for the types your are interested in: `isExactlyNothing` and `isAny`.

2023-01-25 08:38 UTC, odersky commented on compiler/src/dotty/tools/dotc/typer/Typer.scala
> +            val (usingFormal, paramType) =
Not sure why usingFormal is needed here. Why is`knownFormal` not the right condition?

2023-01-26 11:16 UTC, merged