Attach explanation message to diagnostic message
lampepfl/dotty pull request #16787
Opened 2023-01-30 14:23 UTC by lwronski

When the `-explain` flag was turned on, an explanation message wasn't displayed in the Metals and Scala CLI. This was because both of these tools only print the message from the [Problem.message](https://github.com/lampepfl/dotty/blob/c0a7d128671d063a2b566abdaa08fe7fa83c2d06/sbt-bridge/src/dotty/tools/xsbt/Problem.java#L17) field.

To resolve this issue, I attached the explanation content to the `Problem.message` field, which will now be displayed in the Metals and Scala CLI.

This PR addresses a [issue](https://github.com/VirtusLab/scala-cli/issues/1285) from `scala-cli`.

2023-01-30 16:13 UTC, julienrf commented
In the long run, should we pass the `explanation` to _another_ field of `Problem` (just like `diagnosticCode` is a separate field), instead of concatenating it to the `message`?

2023-01-30 17:16 UTC, prolativ commented
`diagnosticCode` should be just what the name says - a code/number of an error. Actually there doesn't  currently seem to be any more suitable field in a `Diagnostic` to carry explanations of messages (note that explanations are not fixed for a given error number but their content can change depending on the actual code that caused the error and what the compiler manages to diagnose). Adding some new field to `Diagnostic` would require changes in LSP, but this doesn't really seem worth the effort as that would only allow us to display explanations in some fancy way but it's actually the content of the explanation message that matters for users

2023-01-31 07:06 UTC, julienrf commented
> Adding some new field to `Diagnostic` would require changes in LSP,

This is indeed what I meant.

>but this doesn't really seem worth the effort as that would only allow us to display explanations in some fancy way but it's actually the content of the explanation message that matters for users

OK, good to know. I thought it could be useful to allow UIs to adapt the amount of information based on the available space. For instance, show first the `message`, but if there is an additional `explanation` then show a button “more details” with the full explanation.

But in practice I don’t really know if those explanations are really verbose or not.

2023-01-31 09:34 UTC, prolativ approved these changes

2023-01-31 10:41 UTC, ckipp01 requested changes
I'd actually recommend not merging this unless I'm misunderstanding.

Regarding usage in scala-cli, wouldn't it be more appropriate to instead of relying on the message to rely on `rendered`? This is what sbt does for example. By adding the explanation to the message we're essentially making rendered useless aren't we? I  don't think we should do this. From my understanding this exact usecase is why `rendered` was introduced.

On another note, @lwronski do you have a screenshot on what this looks like in VS Code? In some editors these errors will be gigantic and probably won't display that nicely. I think before we merge this we should ensure that it actually looks nice in the editor. If i'm not mistaken that's why we didn't do this earlier. I'd also be curious to see how other editors that support LSP will display this. We don't want to introduce this and mutilate the way errors look in a handful of editors, even if it's for a minority of users.

I think if we wanted to carry this information forward a more appropriate way would be use use the `explanation` field in the `DiagnosticCode`.

2023-01-31 14:48 UTC, ckipp01 commented
> Is there any formal requirement on a message to be 'short'? Is there any limit on the length? 

I don't think so, but since using explain has a lot of "structured" output in the string we should probably make sure it looks alright in the actual editor since it will make many of them longer.

> As far as I know the purpose of this flag was actually not limiting the size of error messages but avoiding slowdowns in compilation is a general case when more detailed information about an error was not requested.

Gotcha, that makes sense. However with this approach then what ends up being the difference of `rendered` and `message`?

> Unfortunately CodeDescription specifies only one field href: URI, assuming the explanation to be served externally and fixed for a given type of error.

Ahhh, I didn't even realize it was only a `URI`! That's sort of a bummer but I guess it makes sense. All the more reason to have a stable URI for our diagnostic codes that someone can reference.

> IMO maybe explanation field inside data could be an option but data is there only LSP at the moment

Yea, I'm not fully sold. Mainly because in [LSP](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnostic) anyways it says:

>  A data entry field that is preserved between a `textDocument/publishDiagnostics` notification and `textDocument/codeAction` request.

Which doesn't really seem to apply here or would break assumptions about what it's meant to be used for.

I guess if inside of `message` is the only place to put it, sure, but then the question about the differentiation of `rendered` still stands. Plus we should see what it looks like in various editors as well.

2023-02-01 10:51 UTC, prolativ commented
> I don't think so, but since using explain has a lot of "structured" output in the string we should probably make sure it looks alright in the actual editor since it will make many of them longer.

Explanations can have various shapes but even if we keep them separate from basic messages, I wouldn't say they have much structure that we could handle in a special way (at least not more than basic messages generated without `-explain`)

> Gotcha, that makes sense. However with this approach then what ends up being the difference of rendered and message?

It seems that rendered is mainly intended to be used in a REPL session or when compiling code from the command line. Rendering adds some fancy ways of displaying messages when all the information about an error have to be shown in a single piece of text, e.g. it reprints erroneous lines of code with underlined positions and wraps extra messages in ASCII frames just as shown here https://github.com/VirtusLab/scala-cli/issues/1285

In general our main problem is that extra messages from `-explain` are entirely lost now when code gets compiled via BSP, which should be considered a bug. Of course we might later try to improve the way how things get shown in IDEs, but that would be the next step with lower priority

2023-02-01 10:57 UTC, ckipp01 commented
> Rendering adds some fancy ways of displaying messages when all the information about an error have to be shown in a single piece of text

But isn't this what we're trying to do with including the `-explain` output with the message?

> In general our main problem is that extra messages from -explain are entirely lost now when code gets compiled via BSP, which should be considered a bug.

Totally, agreed.

2023-02-01 13:15 UTC, prolativ commented
>>Rendering adds some fancy ways of displaying messages when all the information about an error have to be shown in a single piece of text

>But isn't this what we're trying to do with including the -explain output with the message?

I would say the compiler and tooling have slightly different understanding of `explanation`. And `rendered` seems to be the entire `Problem`/`Diagnostic` displayed in a fully textual form suitable for presenting in a console

2023-02-01 13:33 UTC, ckipp01 approved these changes

2023-02-01 14:24 UTC, lwronski commented
> IMO maybe `explanation` field inside `data` could be an option but `data` is there only LSP at the moment

@prolativ FYI - The data field is also available in the BSP. It was added some time ago in this PR https://github.com/build-server-protocol/build-server-protocol/pull/363/files.

2023-02-01 17:17 UTC, ckipp01 commented
> @prolativ FYI - The data field is also available in the BSP. It was added some time ago in this PR https://github.com/build-server-protocol/build-server-protocol/pull/363/files.

True, but again I think we want to be careful what we stick in here since this `data` field will be forwarded all the way to the LSP client and we don't want to have to be storing a bunch of stuff client side that might not have anything to do with the original purpose, code actions.

2023-02-03 14:03 UTC, merged