Support extension methods imported from different objects
lampepfl/dotty pull request #17050
Opened 2023-03-06 10:25 UTC by odersky

Add a special case to name resolution so that when expanding an extension method from `e.m` to `m(e)` and `m` is imported by several imports on the same level, we try to typecheck under every such import and pick the successful alternative if it exists and is unambiguous.

Fixes #16920

2023-03-06 12:21 UTC, odersky commented
test performance please

2023-03-06 13:34 UTC, odersky commented
test performance please

2023-03-06 15:41 UTC, odersky commented
@mbovel it seems the benchmark server is down?

2023-03-06 15:59 UTC, mbovel commented
test performance please

2023-03-06 15:59 UTC, mbovel commented
test performance please

2023-03-06 16:17 UTC, mbovel commented
> it seems the benchmark server is down?

Fixed.

2023-03-06 18:06 UTC, odersky commented
test performance please

2023-03-06 19:17 UTC, Ichoran commented
This looks great!  I just wonder if it's necessary to add a test where an import is re-imported at a deeper level to make sure the search for alternatives is maintained.  Something like

```scala
object ReimportSucceeds:
  import One._
  def test: Unit =
    import Two._
    import One._
    "five".wow
```

The reason this is important is that people may want only some extensions in a broader context, but when they switch to a narrower context with more extensions, they may still wish to have the broader extensions available.

For instance, one might want `+` to add `Duration`s everywhere in a file, but to import a file-handling library that uses `+` on `Path` only in one method.  But one might want to do temporal math in that same method.

A bulk reimport is probably a reasonable balance between actual accidental collisions and requiring a bunch of extra boilerplate in order to get the desired functionality.  Does it already work this way by default?  Because I don't know how duplicate but more deeply-nested import statements are handled, I don't know whether this is actually a separate case that needs to be tested.

2023-03-06 19:27 UTC, odersky commented
@ichoran Nested imports take precdence over outer ones, so the example you show should not be a problem.

2023-03-07 09:00 UTC, bishabosha commented
doesnt this require a SIP?

2023-03-07 09:50 UTC, bishabosha requested changes
this should be under experimental import until SIP approval

2023-03-07 09:54 UTC, odersky commented
I agree that this could be a SIP, but I won't have the time to submit and defend it. Would one of you want to take that over?

2023-03-07 09:55 UTC, sjrd commented
I can write the SIP, yes.

2023-03-07 10:47 UTC, odersky commented
For now this requires a language import
```scala
import language.experimental.relaxedExtensionImports`
```
We will drop that requirement once the SIP committee has approved the change.

2023-03-07 22:45 UTC, Ichoran commented
@sjrd - I'm glad you're able to write the SIP!  If it would help to have more motivating examples, I have plenty!

2023-03-08 13:34 UTC, bishabosha requested changes
One of the other problems from [the Contributor's thread](https://contributors.scala-lang.org/t/change-shadowing-mechanism-of-extension-methods-for-on-par-implicit-class-behavior/5831) is that this example still does not work:
```scala
import language.experimental.relaxedExtensionImports
import scala.annotation.targetName

trait Foo[+T]

object Ops:
  extension (foo : Foo[Int])
    @targetName("bazInt")
    def baz : Unit = {}

import Ops.*

extension (foo : Foo[Double])
  @targetName("bazDouble")
  def baz : Unit = {}

@main def Test =
  val f = new Foo[Int] {}
  f.baz //error
```

In this case the `bazDouble` is always chosen because it is not imported, but again surely from the user's point of view it makes sense to also try the valid `Ops.bazInt` that was imported

2023-03-08 13:44 UTC, odersky commented
> In this case the bazDouble is always chosen because it is not imported, but again surely from the user's point of view it makes sense to also try the valid Ops.bazInt that was imported. 

Yes, but that's just wishful thinking. And catering to that would simply produce a huge ball of mud. The current change is already highly problematic for it non-orthogonality. But the argument was that this is an important use case and there was no way to re-arrange things to make it work without the change. By comparison, the latest example is a fringe use case, not worth complicating the rules even further.

2023-03-08 13:53 UTC, bishabosha approved these changes
this is a great improvement over the status quo - and the local scope version always being picked is something that can be easily overcome by application developers

2023-03-10 16:13 UTC, sjrd commented
SIP: https://github.com/scala/improvement-proposals/pull/60

2023-03-21 03:28 UTC, som-snytt commented on docs/_docs/reference/contextual/extension-methods.md
> +  - If `m` is imported by several imports which are all on the nesting level,
`all on the [same] nesting level`

2023-03-21 08:26 UTC, odersky commented on docs/_docs/reference/contextual/extension-methods.md
> +  - If `m` is imported by several imports which are all on the nesting level,
```suggestion
  - If `m` is imported by several imports which are all on the same nesting level,
```

2023-04-22 10:39 UTC, odersky commented
Since SIP 54 just got accepted, I'll remove the experimental language import.

2023-04-22 10:46 UTC, sjrd commented
It's been accepted to be shipped as experimental, at this stage. ;)

2023-04-22 11:10 UTC, odersky commented
Ah indeed, it was labelled stage:design, not stage:implementation.

2023-04-22 19:40 UTC, merged