[WIP] List(...) optimization to avoid intermediate array
lampepfl/dotty pull request #17166
Opened 2023-03-28 17:11 UTC by KuceraMartin

2023-03-28 17:28 UTC, KuceraMartin commented
todo:
- [ ] fix lists of primitive types
- [ ] limit for nested lists
- [ ] more tests

2023-05-04 14:34 UTC, mbovel commented
Hi @KuceraMartin! Would you like to continue working on this PR during the next issue spree? Do you think the TODOs left are easy and could be interesting for beginners to follow along?

2023-05-05 08:06 UTC, KuceraMartin commented
> Hi @KuceraMartin! Would you like to continue working on this PR during the next issue spree? Do you think the TODOs left are easy and could be interesting for beginners to follow along?

Hi @mbovel, actually I'm not sure if this is suitable for another spree.

1. The first todo might be interesting but maybe too easy?
2. For the second one I'm not sure—if I remember correctly, the problem with the Scala 2 implementation was that it was calling `super.transform` recursively to handle the nesting, which we cannot do with the Scala 3 mini phases? But then I think @smarter mentioned he wasn't sure if we should re-implement this nested limit at all.
3. Writing more tests is probably not very interesting.

I was planning to finish the PR by myself. If it doesn't get picked for the spree, I should have time to do it next week.

2023-11-20 14:53 UTC, nicolasstucki requested changes

2023-11-20 14:53 UTC, nicolasstucki commented on compiler/src/dotty/tools/dotc/transform/ArrayApply.scala
> +  private def seqApplyArgsOrNull(tree: Apply)(using Context): JavaSeqLiteral | Null =
We usually avoid nulls like that one. Maybe define a `SeqApply(args)` extractor that covers both `isSeqApply` and `seqApplyArgsOrNull`.

Example use:
```diff
   override def prepareForApply(tree: Apply)(using Context): Context =
-    if isSeqApply(tree) then
-      val args = seqApplyArgsOrNull(tree)
-      if args != null then
-        ctx.fresh.setProperty(TransformListApplyBudgetKey, transformListApplyBudget - args.elems.length)
-     else ctx
-    else ctx
+    tree match
+      case SeqApply(args) => 
+        ctx.fresh.setProperty(TransformListApplyBudgetKey, transformListApplyBudget - args.elems.length)
+      case _ => 
+        ctx
```

2023-11-20 14:53 UTC, nicolasstucki commented on compiler/test/dotty/tools/backend/jvm/ArrayApplyOptTest.scala
> +
Also add tests for 

* `List[Object]("1", "2", "3", "4", "5", "6", List[Object]()) // 7 cons w/ 6 string heads + 1 `
* ` List[Object]("1", "2", "3", "4", "5", List[Object]("6", "7")) // wrap 2`

2023-11-28 10:44 UTC, nicolasstucki approved these changes

2023-11-28 10:44 UTC, merged