WIP: Verify links in docs
lampepfl/dotty pull request #17163
Opened 2023-03-28 13:56 UTC by Dedelweiss

Here is my proposed PR to check that the links in the API comments (@see) are valid and point to valid static documentation.

## Validations:

- [x] The link is valid

- [x] Assets
Example: `![bar.png](/ressources/bar.png)`

- [ ] Static pages
Example: `[foo](./foo.md)`

- [x] API documentation
 Example: `[[com.example.Foo]]`
A validation is already done in [Comments.resolveLink](https://github.com/lampepfl/dotty/blob/main/scaladoc/src/dotty/tools/scaladoc/tasty/comments/Comments.scala). But there is an Issue https://github.com/lampepfl/dotty/issues/17550

## Def ProcessLink:
This function allows to check both that a string is a valid url with the Try, but also that this link leads to an existing static documentation.
When one of these two conditions is not met, a warning is sent when the documentation is generated.
### Result:
<img width="595" alt="Screenshot 2023-03-29 at 12 01 09" src="https://user-images.githubusercontent.com/44496264/228499561-a9ddf2f3-6416-45c8-bf57-a3f891a16c54.png">

## Disable Validation:

### First method

**A yaml in a folder, with each file and sub-folder having a warning validation disabled**.

- Take the path where a method is started
- Verify if a validation.yaml is present in the folder or the previous folder with a line like:
    - noValidation: true
- if yes, disable the warning.

### Second method

**A yaml with a folder list, all the files in each folder have warning validation disabled**

- Search for the generalValidation.yaml file in a specific folder (Like ressource)
- Take the name of each folder in this file
- During the validation @see, if the name of the folder of the file correspond to one of the name in the file, deactivate the warning

Fixes: #16229

2023-03-28 13:58 UTC, Dedelweiss commented
I also wanted to add a check for external urls with the following method:

```val url = new URL(urlString)
  val connection = url.openConnection.asInstanceOf[HttpURLConnection]
  connection.setRequestMethod("GET")
  connection.connect()
  val responseCode = connection.getResponseCode
  connection.disconnect()
if responseCode == 404 then
   report.warn....
```

But with this method, the time to generate the documentation is much more increased, so I found it not very efficient to add it. If you have other methods I am interested.

2023-04-25 15:22 UTC, Florian3k requested changes
This implementation currently generates a lot of false-positives (over 2000) most of which look like this:
```
Link to foreach is not valid
Link to flatMap is not valid
Link to toLeft is not valid
Link to `java.lang.ref.Reference` is not valid
Link to scala.collection.Iterator, method `grouped` is not valid
Link to scala.math.Ordering is not valid
Link to scala.math.Ordering is not valid
Link to scala.collection.Iterator, method `sliding` is not valid
```

It also generates warnings for valid links, such as:
```
Link to https://dotty.epfl.ch/docs/reference/changed-features/numeric-literals will return a 404 not found
```

2023-04-26 15:25 UTC, Dedelweiss commented
Thank you very much for your feedback @Florian3k. 
I have quick question for the reference like `@see isFunctionType`. Are they supposed to be clickable or is it just a non-clickable reference?

2023-04-26 15:36 UTC, Florian3k commented
No, I don't think they're supposed to be clickable.

2023-04-26 15:46 UTC, Dedelweiss commented
> No, I don't think they're supposed to be clickable.

Okay, so don't need to test them I think. I can just test for internal and external (When I will find a way) link.

2023-05-01 08:36 UTC, julienrf commented
> I have a quick question for the reference like `@see isFunctionType`. Are they supposed to be clickable or is it just a non-clickable reference?

They are not supposed to be clickable. Only links formatted as such `[[...]]` are expected to be clickable.

I think scaladoc should only check _internal_ links, not all the links. And there should be an option to exclude some path. See how this is done in [Laika](https://planet42.github.io/Laika/latest/03-preparing-content/02-navigation.html#validated-internal-links), for instance.

2023-05-11 14:24 UTC, Dedelweiss commented
Hi, I looked at how Laika did it to disable the warnings and I noticed two different methods:
## First method

**A yaml in a folder, with each file and sub-folder having a warning validation disabled**.

- Take the path where a method is started
- Verify if a validation.yaml is present in the folder or the previous folder with a line like:
    - noValidation: true
- if yes, disable the warning.

## Second method

**A yaml with a folder list, all the files in each folder have warning validation disabled**

- Search for the generalValidation.yaml file in a specific folder (Like ressource)
- Take the name of each folder in this file
- During the validation @see, if the name of the folder of the file correspond to one of the name in the file, deactivate the warning

So I plan to do both methods, I think I can do a lot of it. But I'm stuck for the beginning, I don't know how to get the path of a file containing the @see in order to know in which folder it is located. 
If someone has an idea, I am very interested. Thank you very much.

2023-05-11 15:35 UTC, julienrf commented
Hey @Dedelweiss, thank you very much for the investigation. I keep thinking that only links within double brackets should be checked, not the content of the `@see` directive. What do you think?

2023-05-12 13:34 UTC, Dedelweiss commented
> Hey @Dedelweiss, thank you very much for the investigation. I keep thinking that only links within double brackets should be checked, not the content of the `@see` directive. What do you think?

Oh yes, I'm sorry, I did misread your previous comment. Indeed it would be better to target more generally the double brackets links in order to test a maximum of them. I'll correct that. Thanks a lot for the feedback.

2023-05-12 14:16 UTC, Dedelweiss commented
Hey @julienrf, looking into it, I noticed that it came back to this [PR#17163](https://github.com/lampepfl/dotty/pull/17163) I did earlier. The problem is that this one is blocked because I'm waiting for a response on the related [issue](https://github.com/lampepfl/dotty/issues/16695).
So, would it be better to continue these validations in the `SiteRenderer` file, in which link validations had already been started, or in the `Preparser` as I did in this PR?
Also, I would be interested if you have an answer to the question of this [issue](https://github.com/lampepfl/dotty/issues/16695). 
Thank you very much Julien.

2023-05-22 12:05 UTC, Dedelweiss commented
Hello @julienrf,
I have a quick question, In your examples you put `[foo](./foo.md)` for a link to a static page from the API documentation. I know this kind of link work from a static page to a static page. However, in my testing, I was unable to link from the API documentation in the same way. I think this feature comes from the [driForLink](https://github.com/lampepfl/dotty/blob/main/scaladoc/src/dotty/tools/scaladoc/site/StaticSiteContext.scala) function and it might explain why it doesn't work in the API documentation. So I don't know if it's just my link that's not good or if it's really that reason. I'm interested if you have an example that works or any information.

2023-05-23 12:52 UTC, julienrf commented
In my opinion, it is very important that “API links” (ie, links to symbols of the API usually written with the wikidoc syntax like `[[scala.collection.Seq]]`) work within the API documentation, and that “page links” (ie, links to pages of the static website like `[foo](./foo.md)`) work within the static pages.

Once that is done, it would be really great to support both types of links everywhere (so, including API links in the static pages and pages links in the API docs).

All that could be done in separate PRs (especially if the “nice to have” one requires significant development).

2026-02-16 17:09 UTC, Gedochao commented
@Dedelweiss @Florian3k is this still relevant? Do you plan to work on this in the near future, or should we close it for now?

2026-02-16 18:59 UTC, Dedelweiss commented
> @Dedelweiss @Florian3k is this still relevant? Do you plan to work on this in the near future, or should we close it for now?

I think we can close it for now

2026-02-16 18:59 UTC, closed without merging