Do not issue deprecation warnings when declaring deprecated case classes
lampepfl/dotty pull request #17165
Opened 2023-03-28 16:58 UTC by jan-pieter

Do trigger a deprecation warning when calling synthetic members of the companion object of a deprecated case class.

Fixes #11022

2023-03-28 16:59 UTC, jan-pieter commented on tests/pos-custom-args/i11022.scala
> +val c = CaseClass(42).magic()
This line _should_ have triggered a warning, but it doesn't

2023-04-24 10:55 UTC, odersky requested changes
Otherwise LGTM. 

Thanks for the contribution!

2023-04-24 10:55 UTC, odersky commented on compiler/src/dotty/tools/dotc/typer/CrossVersionChecks.scala
> +    val toCheck: List[Symbol] = sym :: Option.when(sym.isAllOf(SyntheticMethod))(sym.owner.companionClass).toList
```suggestion
    val toCheck = sym :: (if sym.isAllOf(SyntheticMethod) then sym.owner.companionClass :: Nil else Nil)
```
This is faster and clearer.

2023-04-24 10:55 UTC, odersky commented on compiler/src/dotty/tools/dotc/typer/CrossVersionChecks.scala
> +    for annot <- toCheck.flatMap(_.getAnnotation(defn.DeprecatedAnnot)) do
```suggestion
    for sym <- toCheck; annot <- sym.getAnnotation(defn.DeprecatedAnnot) do
```

2023-04-24 10:55 UTC, odersky commented on compiler/src/dotty/tools/dotc/typer/CrossVersionChecks.scala
> +    for annot <- toCheck.flatMap(_.getAnnotation(defn.DeprecatedAnnot)) do
Again, this is clearer and more efficient.

2023-04-24 10:55 UTC, odersky commented on compiler/src/dotty/tools/dotc/typer/CrossVersionChecks.scala
> +    for annot <- toCheck.flatMap(_.getAnnotation(defn.DeprecatedAnnot)) do
Generally, if there is a language construct doing the job, avoid library calls.

2023-04-24 21:10 UTC, odersky approved these changes

2023-05-01 21:08 UTC, merged