Fix context function type in md file
lampepfl/dotty pull request #17174
Opened 2023-03-29 14:17 UTC by reminia

Expression E's return type should be T according to the context.

2023-03-29 15:12 UTC, SethTisue submitted a review, later dismissed

2023-03-29 15:39 UTC, dwijnand requested changes
No, `E` is the expression, the tree, rewritten to be another tree - a context function literal tree.

2023-03-29 16:10 UTC, SethTisue commented
Doh. I'm tempted to say, “can we adjust the prose to head off this misreading”, but that could just be my embarrassment speaking :-)

2023-03-30 03:54 UTC, reminia commented
> No, `E` is the expression, the tree, rewritten to be another tree - a context function literal tree.

Thanks for pointing out. hmm, that's quite confusing. It took me several times reading to figure it out. If this sentence is putting forward the definition part, I could understand it more easily :)
>>> Like their types, context function literals are written using ?=> as the arrow between parameters and results.

2023-03-30 03:55 UTC, closed without merging