Preserve type bounds for inlined definitions in posttyper
lampepfl/dotty pull request #17190
Opened 2023-03-30 21:31 UTC by Decel

Fixes #17168, as per @odersky idea.

2023-05-04 12:20 UTC, dwijnand approved these changes

2023-05-05 14:45 UTC, nicolasstucki commented on compiler/src/dotty/tools/dotc/transform/PostTyper.scala
> +          super.transform(call)
We still have the issue of the exponential blowup.

2023-05-05 14:47 UTC, nicolasstucki commented on compiler/src/dotty/tools/dotc/transform/PostTyper.scala
> +          super.transform(call)
```suggestion
         transform(call)
```

2023-05-05 14:50 UTC, nicolasstucki commented on compiler/src/dotty/tools/dotc/transform/PostTyper.scala
> +          super.transform(call)
By doing this recursion we will always enable `ctx.compilationUnit.needsInlining = true`.

* https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/transform/PostTyper.scala#L287
* https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/transform/PostTyper.scala#L295
* https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/transform/PostTyper.scala#L348

This is not ideal if the file only contains transparent inline calls.

2023-05-05 14:52 UTC, nicolasstucki requested changes
We have to be more careful with that recursion.

We already know about 2 unintended consequences, and we may be missing something else.

2023-05-05 15:19 UTC, odersky commented
Yes, let's back out of the last commit.

2023-05-05 16:33 UTC, dwijnand commented
The last commit has the wrong indentation.

2023-05-12 08:09 UTC, nicolasstucki reviewed
@Decel commit LGTM. 

@dwijnand could you review the commit I added?

2023-05-15 09:52 UTC, dwijnand approved these changes

2023-05-15 09:52 UTC, merged