Add new HOLETYPES to TASTy format
lampepfl/dotty pull request #17225
Opened 2023-04-11 07:50 UTC by nicolasstucki

This is a new encoding of HOLE that differentiates between type and
term arguments of the hole.

```
HOLE Length idx_Nat tpe_Type (HOLETYPES Length targ_Type*)? arg_Tree*
    -- Splice hole with index `idx`, the type of the hole `tpe`, type arguments of the hole `targ`s and term arguments of the hole `arg`s

Based on #17144

2023-04-11 14:30 UTC, smarter requested changes

2023-04-11 14:30 UTC, smarter commented on tasty/src/dotty/tools/tasty/TastyFormat.scala
> +                                                                                      -- Note: From 3.0 to 3.3 `args` could contain type arguments as well. This is no longer the case.
To be clear, args when you say "type arguments" here you mean TypeTrees, as opposed to the use of "type arguments" in the previous sentence where they are Types?

2023-04-12 08:11 UTC, nicolasstucki commented on compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
> +      TastyQuoteHole(true, idx, targs ::: args, TypeTree(tpe)).withType(tpe)
Maybe not. It is useful to have it in the TASTy HOLE. But we might be able to remove it from here.

2023-04-12 08:50 UTC, nicolasstucki commented on compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
> +      TastyQuoteHole(true, idx, targs ::: args, TypeTree(tpe)).withType(tpe)
If we remove it, we don't have a way to retype the tree. I do not have another way to infer the type of hole. This is an issue when Ychecking the tree.

2023-04-12 14:14 UTC, smarter commented on compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala
> +      TastyQuoteHole(true, idx, targs ::: args, TypeTree(tpe)).withType(tpe)
The TreeChecker uses `promote` to retype tree with their existing type.

2023-04-18 08:40 UTC, closed without merging