Warn when calling synchronized on Predef or on synthetic file objects
lampepfl/dotty pull request #17449
Opened 2023-05-09 17:59 UTC by mbovel

Fixes #17266

2023-05-09 18:03 UTC, mbovel commented
We should probably extend that to `wait`, `notify` and maybe other `AnyRef` methods.

2023-05-10 09:20 UTC, mbovel commented on compiler/test/dotty/tools/dotc/CompilationTests.scala
> +      compileFilesInDir("tests/neg-custom-args/explain", defaultOptions.and("-Xfatal-warnings", "-explain")),
Done ✅

2023-05-10 09:20 UTC, mbovel commented
> We should probably extend that to wait, notify and maybe other AnyRef methods.

Done ✅

2023-05-10 19:34 UTC, som-snytt commented
As motivation, I just did this on Scala 2!

That was using `eq` from a value class. It doesn't root import from `Predef`, but the class had an explicit import.

The unreliable Scala 2 equality warning gave me a heads up, but linting all such selections seems safer. I haven't checked if `eq` is covered here. This Scala 2 ticket is just about the message:

https://github.com/scala/bug/issues/12785

2023-05-10 20:38 UTC, som-snytt commented on compiler/src/dotty/tools/dotc/reporting/messages.scala
> +       |resolved to calls on ${hl("Predef")}. This might not be what you intented."""
typo `intended`

2023-05-10 20:38 UTC, som-snytt commented on compiler/src/dotty/tools/dotc/reporting/messages.scala
> +       |what you intented."""
same cut/paste

2023-05-10 21:39 UTC, dwijnand commented on compiler/src/dotty/tools/dotc/typer/RefChecks.scala
> +    if symbol.exists && (symbol.owner == defn.ObjectClass || symbol.owner == defn.AnyClass) then
Perhaps we can add the last two stooges and go for
```suggestion
    if symbol.exists && defn.topClasses.contains(symbol.owner) then
```

2023-05-10 21:41 UTC, dwijnand approved these changes
LGTM.  Merge when you're happy to stop extending.

2023-05-11 12:48 UTC, odersky commented
I'd like us to try a different warning. Predef is really not so special, after all. Consider this example:
```scala
object O

@main def foo =
  import O.*
  println(getClass)
```
This will print the `O$`, but it arguably should not. 

I think the warning should instead be triggered by this condition:

> When referring to a method from `Any` or `AnyRef` using a single identifier, one must be inside a named class or object (package objects don't count). 

Note that if we put the code in a class like this:
```scala
object O
object C:
  @main def foo =
    import O.*
    println(getClass)
```
we get a different warning, which is what we want:
```
6 |    println(getClass)
  |            ^^^^^^^^
  |            Reference to getClass is ambiguous.
  |            It is both defined in object C
  |            and imported subsequently by import O._
  |
  | longer explanation available when compiling with `-explain`
```

2023-05-11 12:53 UTC, odersky requested changes
By contrast see much less of an issue if we write `this.getClass` at the toplevel. Excluding this without excluding use of `this` in package objects as a whole looks unsystematic.

So either disallow all explicit uses of `this` in package objects or allow them all.

2023-05-11 16:31 UTC, mbovel commented
@odersky I changed to condition to:

```scala
if tree.symbol.exists
   && defn.topClasses.contains(tree.symbol.owner)
   && (!ctx.owner.enclosingClass.exists || ctx.owner.enclosingClass.isPackageObject) then
  report.warning(UnqualifiedCallToAnyRefMethod(tree, tree.symbol), tree)
```

Seems to do what we want. What do you think?

2023-05-11 20:01 UTC, odersky approved these changes
Otherwise LGTM

2023-05-11 20:01 UTC, odersky commented on compiler/src/dotty/tools/dotc/typer/RefChecks.scala
> +  def checkSynchronizedCall(tree: Tree)(using Context) =
Maybe rename that to `checkAnyMemberCall` or something like that?

2023-05-11 21:38 UTC, merged