Spec: Rewrite the type system fundamentals.
lampepfl/dotty pull request #17447
Opened 2023-05-09 16:09 UTC by sjrd

There are two fundamental differences between the type sytems of Scala 2 and 3, which made a fundamental rewrite desirable:

- Scala 2 defines path-dependent types in terms of type projections, whereas Scala 3 is path-dependent first, and has not general type projects.
- Scala 2 has ad hod higher-kinded type parameters and polymorphic type aliases, whereas Scala 3 has first-class type lambdas and is fundamentally higher order.

We therefore rewrite the entire type system section of the spec to be higher-kinded and path-dependent first. In the process, we also revise refined types to better fit the path-dependent nature.

I (sjrd) took the liberty to add myself as a contributor in the index page of the spec, as I believe this constitutes a fundamental contribution to the language specification.

---

The rendered version of the Types chapter can be seen here:
[Types Scala 3.pdf](https://github.com/lampepfl/dotty/files/11433246/Types.Scala.3.pdf)

2023-06-06 11:43 UTC, odersky requested changes
I like the new structure. It's a great improvement to what we had before.

2023-06-06 11:43 UTC, odersky commented on docs/_spec/03-types.md
> -
The section on Volatile types should be dropped. It is replaced by a notion of realizability.

The section on Erasure should be updated to the new rules. 

Generally, all usages of compound types (using `with`) should be dropped.

2023-06-06 11:43 UTC, odersky requested changes
I like the new structure. It's a great improvement to what we had before.

2023-06-06 12:46 UTC, sjrd commented on docs/_spec/03-types.md
> +TypeLambda            ::= TypeLambdaParams ‘=>>’ Type
The official rendering is HTML. I posted the PDF as an easy-to-distribute form, but I directly printed from the browser to get it. If we need the PDF to be a truly public document, it seems there are a number of other things that don't render well; notably lines seem to be cut across pages.

2023-06-06 12:48 UTC, sjrd commented on docs/_spec/03-types.md
> +´T[T_1, ..., T_n]´ is an _applied class type_ if and only if ´T´ is a [class type](#type-designators).
Ah yes, parameterized class type is better.

2023-06-06 12:50 UTC, sjrd commented on docs/_spec/03-types.md
> +When "copied" through substutition, all the copies retain the same ´\alpha´, and are therefore equivalent.
I feel like that is what the paragraph just above says. Is there something missing or unclear there?

> Skolem types cannot directly be written in the concrete syntax. Moreover, although they are proper types, they are never inferred as the type given to terms. Skolem types are exclusively used temporarily during subtyping derivations.

2023-06-06 12:53 UTC, odersky commented on docs/_spec/03-types.md
> +When "copied" through substutition, all the copies retain the same ´\alpha´, and are therefore equivalent.
Where does it say that skolem types are not part of inferred types?

2023-06-06 13:03 UTC, sjrd commented on docs/_spec/03-types.md
> +When "copied" through substutition, all the copies retain the same ´\alpha´, and are therefore equivalent.
> they are never inferred as the type given to terms

I guess you're saying we should say they are never inferred *anywhere*, including type arguments and things like that?

2023-06-06 13:09 UTC, odersky commented on docs/_spec/03-types.md
> +When "copied" through substutition, all the copies retain the same ´\alpha´, and are therefore equivalent.
No, the rule is that they cannot be part of inferred types of vals or defs.

2023-06-06 13:12 UTC, sjrd commented on docs/_spec/03-types.md
> +Syntactically, the types `S | T` and `S & T` are infix types, where the infix operators are `|` and `&`, respectively (see [infix types](#infix-types)).
> In line 711 below we have: "If ´C´ is invariant, emit a compile error". What is that supposed to mean? I can certainly write such a type:
> 
> ```scala
> class Ref[X]
> // defined class Ref
>                                                                                                                        
> scala> def x: Ref[Int] & Ref[String] = ???
> ```

Hum, this came from the [Scala 3 reference](https://docs.scala-lang.org/scala3/reference/new-types/intersection-types-spec.html). But I agree that it doesn't seem to make sense. I'll remove the third rule and only keep the first two.

2023-06-06 15:30 UTC, sjrd commented on docs/_spec/03-types.md
> -
Weak conformance will be the subject of a separate PR that introduces harmonization, so I would rather not touch it now.

I updated erasure. For the volatile types I'll have to investigate how realizability affects that section.

2023-06-06 15:36 UTC, sjrd commented
I think I have addressed everything so far except the Volatile Types -> Realizable comment.

2023-06-07 08:32 UTC, sjrd commented
Volatility now replaced by realizability as well.

2023-06-07 12:35 UTC, merged