test: add in a regression test for #9270
lampepfl/dotty pull request #17485
Opened 2023-05-12 11:26 UTC by ckipp01

Closes #9270

2023-05-12 12:07 UTC, nicolasstucki requested changes

2023-05-12 12:07 UTC, nicolasstucki commented on tests/pos/i9270.scala
This one should be in `tests/run/i9270.scala`

2023-05-12 12:07 UTC, nicolasstucki commented on tests/pos/i9270.scala
> +@main def test() =
```suggestion
@main def Test() =
```

2023-05-12 14:28 UTC, ckipp01 commented on tests/pos/i9270.scala
Ah, my bad. Huh, it's odd though, so this does indeed fail the test just like was outlined in the original issue. However, when running this with `scala-cli` for example, you don't get an issue. I was surprised to see this difference.

Also, what's sort of the rule with having a test like this that fails and adding it to the excludes file. Like since I already have this and it does indeed fail, I'm assuming I can just move it and then add it to the `run-test-recheck.excludes`, but is adding a bunch of stuff to the excludes something that is desirable?

2023-05-18 09:39 UTC, ckipp01 commented
Based on the convo in the last Dotty meeting about not really wanting to add a bunch of tests to this list, I'll go ahead and close this.

2023-05-18 09:39 UTC, closed without merging