Merge 3.3.0 reference
lampepfl/dotty pull request #17587
Opened 2023-05-25 14:23 UTC by Kordyjan

2023-05-25 15:07 UTC, julienrf commented on docs/_docs/reference/contextual/derivation.md
I am not sure about the changes in this file. @bishabosha could you please double check?

2023-05-25 15:43 UTC, bishabosha commented on docs/_docs/reference/contextual/derivation.md
this change is ok, (all I see is h3 changing to h2)

2023-05-26 11:19 UTC, prolativ approved these changes

2023-05-26 11:46 UTC, bishabosha requested changes
we really should update https://github.com/lampepfl/dotty/blob/release-3.3.0/docs/_docs/reference/language-versions/source-compatibility.md to list `-source 3.3` mode

2023-05-29 14:28 UTC, Kordyjan commented
I don't think we have a version picker for the language reference. It exists only for API docs.
Language ref is always synchronized with `language-reference-stable`.

2023-05-29 19:22 UTC, bishabosha commented on docs/_docs/reference/language-versions/source-compatibility.md
>  - [`future-migration`](https://scala-lang.org/api/3.x/scala/runtime/stdLibPatches/language$$future-migration$.html): Same as `future` but with additional helpers to migrate from `3.2`. Similarly to t
```suggestion
- [`future-migration`](https://scala-lang.org/api/3.x/scala/runtime/stdLibPatches/language$$future-migration$.html): Same as `future` but with additional helpers to migrate from `3.3`. Similarly to the helpers available under `3.0-migration`, these include migration warnings and optional rewrites.
```

2023-05-30 07:24 UTC, merged