Fix selecting terms using _root_
lampepfl/dotty pull request #18335
Opened 2023-08-03 08:14 UTC by dwijnand

2023-08-07 08:57 UTC, odersky requested changes
I find this deeply inelegant. Checking for _root_ when parsing every ident is terrible. 

We should disallow definitions of _root_ in valdefs or defdefs instead. That's the cleaner fix.

2023-08-07 09:02 UTC, odersky commented
Or do nothing and let the chips fall, which was the state before. I believe it is much preferable to just leave _root_ as regular an identifier and live with malicious code that defines alternates than to mess up the parser like this. 

That's why it was like this in the first place. The suspicion was that it's not a bug worth fixing, i.e. the fix would likely be worse than the bug. The change in this PR confirms that suspicion for me.

So if we do anything, we can try to rule out definitions. Or revert to the status quo before we decided to change things with `_root_`.

2023-08-07 11:43 UTC, som-snytt commented
Ginseng is a select root.

Scala 2 does the opposite and merely lints the usage, placing no additional restrictions. It's only a backstop.

```
scala> object x { object _root_ { def y = 42 } }; x._root_.y
object x
val res0: Int = 42

scala> object x { object _root_ { def y = 42 }; def z = _root_.y }; x._root_.y
                                                               ^
       error: object y is not a member of package <root>
                                                        ^
       warning: _root_ in root position of qualifier refers to the root package, not object _root_ in object x, which is in scope

scala>
```

2023-08-07 18:15 UTC, dwijnand commented
We only check val/def definitions now.

2023-08-07 18:31 UTC, odersky reviewed
I thought we could not burden Parser with this, but check later at Typer? is there a reason not to do this?

2023-08-08 07:39 UTC, dwijnand commented
> I thought we could not burden Parser with this, but check later at Typer? is there a reason not to do this?

It seemed like logic that is simple enough it _could_ be done in Parser.  I'll have a look at what it looks like done in Typer.

2023-08-08 12:49 UTC, odersky requested changes

2023-08-08 12:49 UTC, odersky commented on tests/neg/i18020.scala
> +  package _root_ { // not-reported
I think we should report an error here as well. (in typedPackageDef)

2023-08-08 12:49 UTC, odersky commented on compiler/src/dotty/tools/dotc/typer/Typer.scala
> +    if name == nme.ROOTPKG then report.error(em"Illegal use of root package name.", ddef)
Maybe factor out into a method in Checking since it is used twice (or 3 times with packages)?

2023-08-08 12:49 UTC, odersky commented on compiler/src/dotty/tools/dotc/typer/Typer.scala
> +    if name == nme.ROOTPKG then report.error(em"Illegal use of root package name.", ddef)
Position should be `ctx.source.atSpan(ddef.nameSpan)`. Then it's precisely the name that is highlighted.

2023-08-08 21:18 UTC, som-snytt commented
Comment from ten years ago (as I was spelunking today):
```
@adriaanm said:
Optimization == evil.root
```
I propose we update the pun to `_root_.evil`.

That may also be theologically more sound.

2023-08-08 21:25 UTC, som-snytt commented
Tests failures of the form
```
 Test 'tests/run-staging/i3876-b.scala' failed with output:                      

  exception while retyping package _root_ {
  class Generated$Code$From$Quoted() extends Object() {
    def apply: Any =
      {
        def f(x: Int): Int = x.+(x)
        f(3)
      }
  }
} of class PackageDef # -1
```
but I'm rooting for you!

2023-08-09 10:13 UTC, odersky approved these changes
Interesting that we need that for reflection. But yes, makes sense.

2023-08-14 20:36 UTC, merged

2023-11-30 10:37 UTC, Kordyjan commented
I assume it is a follow-up to #18187, so leaving it out of lts unless there is significant interest.