Handle dependent context functions
lampepfl/dotty pull request #18443
Opened 2023-08-22 13:29 UTC by nicolasstucki

Add `FunctionTypeOfMethod` extractor that matches any kind of function and return its method type.

We use this extractor instead of `ContextFunctionType` to all of
 * `ContextFunctionN[...]`
 * `ContextFunctionN[...] { def apply(using ...): R }` where `R` might be dependent on the parameters.
 * `PolyFunction { def apply(using ...): R }` where `R` might be dependent on the parameters. Currently this one would have at least one erased parameter.

2023-08-30 06:39 UTC, odersky requested changes
Otherwise LGTM

2023-08-30 06:39 UTC, odersky commented on compiler/src/dotty/tools/dotc/core/Definitions.scala
> +        case RefinedType(parent, nme.apply, mt: MethodOrPoly)
I'd try to optimize it further by inlining the FunctionOf extractor and specializing it to this use case.
Also, maybe split the `RefinedType` match into two, one for `MethodType` refinements and the other for `PolyType` refinements?

2023-10-01 15:06 UTC, odersky commented
@nicolasstucki Can you have a look at the test failure? happy to review again when it is green.

2023-10-13 07:32 UTC, nicolasstucki commented
@odersky now the CI passed.

2023-11-13 17:18 UTC, odersky approved these changes
This will be very handy to have. Sorry for dropping the ball on the reviews.

2023-11-14 09:00 UTC, merged