New capture escape checking based on levels
lampepfl/dotty pull request #18463
Opened 2023-08-27 21:25 UTC by odersky

A new scope restriction scheme for capture checking based on levels.

The idea is to have a stack of capture roots where inner capture roots are super-captures of outer roots.

Refines and supersedes #18348

2023-09-04 14:55 UTC, Linyxus requested changes
Otherwise LGTM!

2023-09-04 14:55 UTC, Linyxus commented on compiler/src/dotty/tools/dotc/ast/TreeInfo.scala
> +   */
```suggestion
  /** An extractor for eta expanded `mdef` or an eta-expansion of a method reference. To recognize this, we use
   *  the following criterion: A method definition is an eta expansion, if
   *  it contains at least one term paramter, the parameter has a zero extent span,
   *  and the right hand side is either an application or a closure with
   *  an anonymous method that's itself characterized as an eta expansion.
   */
```

2023-09-04 16:34 UTC, odersky commented on compiler/src/dotty/tools/dotc/cc/Setup.scala
> +      def inverse = thisMap
No, the inverse of the inverse is thisMap .

2023-09-04 21:04 UTC, Linyxus commented on compiler/src/dotty/tools/dotc/cc/Setup.scala
> +      def inverse = thisMap
Ah, yes, sorry for the false alarm.

2023-09-05 07:40 UTC, Linyxus approved these changes

2023-09-09 10:55 UTC, merged