Convert List.apply into `::` chains
lampepfl/dotty pull request #18567
Opened 2023-09-18 18:47 UTC by lolgab

Reasoning:
Varargs in Scala use intermediate collections as shown in this example:
```scala
def foo = List("", "", "")
def bar = "" :: "" :: "" :: Nil
```

compiling with `-Xprint:repeatableAnnotations` gives:
```scala
def foo(): scala.collection.immutable.List =
  List().apply(scala.runtime.ScalaRunTime.wrapRefArray(["","","" : String]))
    .asInstanceOf[scala.collection.immutable.List]
def bar(): scala.collection.immutable.List = Nil().::("").::("").::("")
```

I want to avoid instantiating that extra `Array` and wrapping it into an `ArraySeq` to then create a `List`.

2023-09-18 19:09 UTC, filipwiech commented
Related issue: 17035. :+1:

2023-09-19 07:43 UTC, nicolasstucki commented
This is less idiomatic in many cases. Do we have a noticeable performance gain?

2023-09-19 07:48 UTC, nicolasstucki commented on compiler/src/dotty/tools/dotc/transform/CheckUnused.scala
> +        val unsorted = sortedImp ++
This has quadratic complexity. Use `:::` instead of `++`.

2023-09-19 09:56 UTC, nicolasstucki requested changes
It would be better to keep the code with the `List.apply` and implement the optimization in https://github.com/lampepfl/dotty/issues/17035.

2023-09-19 10:16 UTC, lolgab commented
> It would be better to keep the code with the `List.apply` and implement the optimization in #17035.

Thank you for the review.
I wasn't aware of the WIP optimization for `List.apply`.

2023-09-19 10:16 UTC, closed without merging

2023-09-19 11:34 UTC, nicolasstucki commented
We should keep the changes from `++` to `:::`. Those do have a performance benefit.

2023-09-19 14:23 UTC, SethTisue commented
> This has quadratic complexity

I don't think there is any complexity difference. Neither `++` nor `:::` copies the right-hand list:

```
scala> val l1 = List(1, 2); val l2 = List(3, 4)
val l1: List[Int] = List(1, 2)
val l2: List[Int] = List(3, 4)
                                                                                                    
scala> (l1 ::: l2).drop(2) eq l2
val res0: Boolean = true
                                                                                                    
scala> (l1 ++ l2).drop(2) eq l2
val res1: Boolean = true
```