Add `-experimental` compiler flags
lampepfl/dotty pull request #18571
Opened 2023-09-19 08:59 UTC by nicolasstucki

When enabled, all top-level definitions are annotated as `@experimental`. This implies that all experimental language features and definitions can be used in this project.

Note that this does not change the strong guarantees on stability of non-experimental code. The experimental features can only be used in a experimental scope (transitively).

2023-09-19 13:22 UTC, nicolasstucki commented on tests/pos/expeimental-flag.scala
> +//> using options -experimental -Yno-experimental
`-Yno-experimental` is set to disable experimental features on this snapshot. `-experimental` is set to add `@experimental` to the top-level definitions.

2023-10-01 14:41 UTC, odersky requested changes
Otherwise LGTM

2023-10-01 14:41 UTC, odersky commented on compiler/src/dotty/tools/dotc/transform/PostTyper.scala
> +        (sym.owner.is(Package) || (sym.owner.name.isPackageObjectName && !sym.isConstructor))
```suggestion
        (sym.owner.is(Package) || (sym.owner.isPackageObject && !sym.isConstructor))
```

2023-10-01 14:41 UTC, odersky commented on docs/_docs/reference/experimental/overview.md
> +This flag will make all top-level definitions have the `@experimental` annotation. This effectively enables the use of any experimental language feature in the project.
```suggestion
This flag enables the use of any experimental language feature in the project. It does this by adding 
an `@experimental` annotation to all top-level definitions. Hence, dependent projects also have to be experimental.
```

2023-10-01 14:41 UTC, odersky commented on docs/_docs/reference/other-new-features/experimental-defs.md
> +This flag will make all top-level definitions have the `@experimental` annotation. This effectively enables the use of any experimental definition or language feature in the project.
Same change as in overview.

2023-11-13 17:22 UTC, odersky approved these changes
LGTM for now.

Should this go into the tasty attribute that contains already the other tags instead of being a separate annotation? If yes, that could be done in a follow-on PR.

2023-11-14 08:45 UTC, nicolasstucki commented
> Should this go into the tasty attribute that contains already the other tags instead of being a separate annotation? If yes, that could be done in a follow-on PR.

Technically it could work. Not sure if it would be benefitial.

2023-11-14 08:45 UTC, merged

2024-12-22 15:07 UTC, joroKr21 commented
Could this be backported to LTS 3.3?

2025-01-13 11:53 UTC, visma-alexander-maslov commented
Backporting it to LTS would really be nice. For example there is no more way to use scalamock 7.x for the project depending on the LTS scala :( 
https://github.com/paulbutcher/ScalaMock/issues/567#issuecomment-2586728841

2025-01-14 16:13 UTC, prolativ commented
After some discussions within the compiler team it was decided that this should not be backported to 3.3 LTS, which focuses on stability rather than using experimental features