Add missing -Yexplicit-nulls for presentation compiler
lampepfl/dotty pull request #18776
Opened 2023-10-27 17:01 UTC by rochala

With a new definition of untyped trees, it is now required to have `-Yexplicit-nulls` flag in modules that use them in order to have proper type checking. This PR adds the missing flag.

Without the flag, it was possible to first assign untyped trees to typed trees, and secondly use extension methods for typed trees which can be seen at `KeywordsCompletions.scala` with usage of `untpdTree.filterSubtrees`.

It is also blocked by: https://github.com/lampepfl/dotty/issues/18775

I can also make a workaround in the unmanaged module, but it will require a dependency on nightly version / a new release from metals.

2023-11-06 08:42 UTC, tgodzik requested changes
Mostly very minor stuff, though I don't love that we need to do nn on everything coming from Java :/ Using project Lombok would help at some point?

2023-11-06 08:42 UTC, tgodzik commented on presentation-compiler/src/main/dotty/tools/pc/AutoImports.scala
> +            editPos.getStart.nn.getCharacter == 0
```suggestion
            editPos.getStart().nn.getCharacter() == 0
```
I guess this errors out only for Scala code, but I would keep it consistent.

2023-11-06 08:42 UTC, tgodzik commented on project/Build.scala
> +    val mtagsVersion = "1.1.1"
We can bump to the latest snapshot

2023-11-06 08:42 UTC, tgodzik commented on presentation-compiler/src/main/dotty/tools/pc/ConvertToNamedArgumentsProvider.scala
> +import scala.language.unsafeNulls
Why unsafeNulls if you use nn in the file anyway?

2023-11-06 08:42 UTC, tgodzik commented on presentation-compiler/src/main/dotty/tools/pc/HoverProvider.scala
> +      ju.Optional.empty.nn
```suggestion
      ju.Optional.empty().nn
```

2023-11-06 08:42 UTC, tgodzik commented on presentation-compiler/src/main/dotty/tools/pc/HoverProvider.scala
> +      ju.Optional.empty.nn
```suggestion
      ju.Optional.empty().nn
```

2023-11-06 08:42 UTC, tgodzik commented on presentation-compiler/src/main/dotty/tools/pc/HoverProvider.scala
> +              ju.Optional.empty.nn
```suggestion
              ju.Optional.empty().nn
```

2023-11-06 08:42 UTC, tgodzik commented on presentation-compiler/src/main/dotty/tools/pc/PcCollector.scala
> +  val uri = params.uri.nn
```suggestion
  val uri = params.uri().nn
```

2023-11-06 08:42 UTC, tgodzik commented on presentation-compiler/src/main/dotty/tools/pc/PcDefinitionProvider.scala
> +    if result.locations.nn.isEmpty then fallbackToUntyped(pos)(using ctx)
```suggestion
    if result.locations().nn.isEmpty() then fallbackToUntyped(pos)(using ctx)
```

2023-11-06 08:42 UTC, tgodzik commented on presentation-compiler/src/main/dotty/tools/pc/PcInlineValueProviderImpl.scala
> +  val text = params.text.nn.toCharArray.nn
```suggestion
  val text = params.text.nn.toCharArray().nn
```

2023-11-06 08:42 UTC, tgodzik commented on presentation-compiler/src/main/dotty/tools/pc/PcInlineValueProviderImpl.scala
> +  val position: l.Position = pos.toLsp.getStart.nn
```suggestion
  val position: l.Position = pos.toLsp.getStart().nn
```

2023-11-06 08:42 UTC, tgodzik commented on presentation-compiler/src/main/dotty/tools/pc/completions/CompletionProvider.scala
> +                    v.insertText.getOrElse( ident.backticked(backtickSoftKeyword) + completionTextSuffix),
```suggestion
                    v.insertText.getOrElse(ident.backticked(backtickSoftKeyword) + completionTextSuffix),
```

2023-11-06 08:42 UTC, tgodzik commented on presentation-compiler/src/main/dotty/tools/pc/completions/Completions.scala
> +            val name = o.label.toLowerCase.nn
```suggestion
            val name = o.label.toLowerCase().nn
```

2023-11-06 08:42 UTC, tgodzik commented on presentation-compiler/src/main/dotty/tools/pc/completions/InterpolatorCompletions.scala
> +    InterpolationSplice(pos.span.point, text.toCharArray.nn, text) match
```suggestion
    InterpolationSplice(pos.span.point, text.toCharArray().nn, text) match
```

2023-11-06 09:57 UTC, rochala commented
Well, this is a tradeoff of having crashes from working on untyped trees as on typed ones, which are significantly harder to debug than simple null pointer assertion failure. They will also fail fast instead of some deeper place in the code. The cost of this is the `nn` or if you are sure that you won't be operating on trees, especially untyped, you can do an import instead. I don't know project Lombok, so I'm not sure if it can help, but adding another library for such small inconvenience is not worth it, at least in my opinion.

2023-11-08 16:15 UTC, tgodzik approved these changes
LGTM!

2023-11-08 18:14 UTC, merged