[WIP] Get generic signature of fields entered after erasure from their corresponding accessor
lampepfl/dotty pull request #19207
Opened 2023-12-05 18:45 UTC by EugeneFlesselle

Fix #17069 

@mbovel

2023-12-08 13:24 UTC, sjrd requested changes

2023-12-08 13:24 UTC, sjrd commented on tests/generic-java-signatures/17069.scala
> +  assert(tpe == tpe2)
This test will still pass if *both* the field and getter have broken signatures. We should also actually test the structure of `tpe`.

2023-12-08 16:37 UTC, sjrd commented
LGTM. Would you mind squashing all the commits in a single one? The individual commits here don't bring any value for the future user of `git blame`.

2023-12-08 22:27 UTC, sjrd approved these changes

2023-12-08 22:27 UTC, merged

2025-02-11 20:20 UTC, som-snytt commented
@sjrd thank-you for encouraging squashing, as it improved my bisecting experience.

I suggested on the linked ticket that this might be backportable but I haven't tried it. Maybe I can just try it.

2025-02-11 20:30 UTC, SethTisue commented
Did somebody think it would be hard to backport? Or was it considered unwise to mess with generic signatures in a point release?

2025-02-11 21:17 UTC, EugeneFlesselle commented
> Did somebody think it would be hard to backport? Or was it considered unwise to mess with generic signatures in a point release?

\cc@hamzaremmal might be informed regarding this