Update `staging.Compiler.make` documentation
lampepfl/dotty pull request #19428
Opened 2024-01-12 07:43 UTC by nicolasstucki

This addresses part of #19211, #19170, and #19176

2024-01-12 07:44 UTC, nicolasstucki commented
@christophkoch This update of documentation should unblock your use cases.

2024-01-12 16:09 UTC, jchyb requested changes

2024-01-12 16:09 UTC, jchyb commented on staging/src/scala/quoted/staging/QuoteDriver.scala
> +                   |The classloader used for the `staging.Compiler` instance might be the correct one.
```suggestion
                   |The classloader used for the `staging.Compiler` instance might not be the correct one.
```

2024-01-12 16:11 UTC, jchyb commented on staging/src/scala/quoted/staging/QuoteDriver.scala
> +                   |The classloader used for the `staging.Compiler` instance might be the correct one.
I think you have lost the `not` here, everything else looks good to me

2024-01-15 13:33 UTC, jchyb approved these changes

2024-01-18 10:35 UTC, merged