Presentation compilers and exports
lampepfl/dotty pull request #19494
Opened 2024-01-19 19:31 UTC by dwijnand

- Fix export go-to-definition
- Par back sourceSymbol usage, to keep some non-source
- Alternatively, make export method synthetic & handle that
- Back to non-synthetic, handle only exported types

2024-01-22 10:14 UTC, dwijnand commented
@odersky let me know if you can spot a better way to do this, or any tweaks in how I do it.

2024-01-29 14:04 UTC, tgodzik approved these changes
This is awesome! Thanks! Probably Martin is still needed to review, but from my side it looks good!

2024-01-30 16:33 UTC, odersky requested changes
Otherwise LGTM

2024-01-30 16:33 UTC, odersky commented on compiler/src/dotty/tools/dotc/core/Symbols.scala
> +          case tree: DefDef if tree.name == name => methPart(tree.rhs).tpe
I don't see how this would work for overloaded exported symbols? Don't we want to compare tree.symbol and denot.symbol instead?

2024-01-31 16:00 UTC, merged