Attempt to inline by name matcher methods
lampepfl/dotty pull request #19631
Opened 2024-02-06 14:12 UTC by yilinwei

This is part of the attempt to get #19577 working without an allocation and using a by name matcher.

The current test `by-inline.scala` failed prior to the changes the following stacktrace:

<details>

```
error while checking tests/pos/byname-inline.scala after phase MegaPhase{protectedAccessors, extmethods, uncacheGivenAliases, checkStatic, elimByName, hoistSuperArgs, forwardDepChecks, specializeApplyMethods, tryCatchPatterns, patternMatcher} ***

  unhandled exception while running Ycheck on tests/pos/byname-inline.scala

  An unhandled exception was thrown in the compiler.
  Please file a crash report here:
  https://github.com/lampepfl/dotty/issues/new/choose
  For non-enriched exceptions, compile with -Yno-enrich-error-messages.

     while compiling: tests/pos/byname-inline.scala
        during phase: Ycheck
                mode: Mode(ImplicitsEnabled,ReadPositions)
     library version: version 2.13.12
    compiler version: version 3.4.1-RC1-bin-SNAPSHOT-nonbootstrapped-git-641ab7a
            settings: -Xsemanticdb true -Xunchecked-java-output-version 9 -Xverify-signatures true -Ycheck List(all) -Yforce-sbt-phases true -Yno-deep-subtypes true -Yno-double-bindings true -Ysafe-init true -classpath /home/yilin/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.12/scala-library-2.13.12.jar:/home/yilin/devel/github/dotty/library/../out/bootstrap/scala3-library-bootstrapped/scala-3.4.1-RC1-bin-SNAPSHOT-nonbootstrapped/scala3-library_3-3.4.1-RC1-bin-SNAPSHOT.jar:out/compilePos/pos/byname-inline -color never -d out/compilePos/pos/byname-inline -indent true -pagewidth 120
[=======================================>] completed (1/1, 1 failed, 0s)
Fatal compiler crash when compiling: tests/pos/byname-inline.scala:
assertion failed: x4.isEmpty
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
	at dotty.tools.dotc.transform.Inlining$$anon$1.traverse(Inlining.scala:51)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1796)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1796)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.fold$1(Trees.scala:1660)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1662)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1693)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1797)
	at dotty.tools.dotc.transform.Inlining$$anon$1.traverse(Inlining.scala:53)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1796)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1796)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1695)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1797)
	at dotty.tools.dotc.transform.Inlining$$anon$1.traverse(Inlining.scala:53)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1796)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1796)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1693)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1797)
	at dotty.tools.dotc.transform.Inlining$$anon$1.traverse(Inlining.scala:53)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1796)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1796)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.fold$1(Trees.scala:1660)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1662)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1693)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1797)
	at dotty.tools.dotc.transform.Inlining$$anon$1.traverse(Inlining.scala:53)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1796)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1796)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1703)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1797)
	at dotty.tools.dotc.transform.Inlining$$anon$1.traverse(Inlining.scala:53)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1796)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1796)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1693)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1797)
	at dotty.tools.dotc.transform.Inlining$$anon$1.traverse(Inlining.scala:53)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1796)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1796)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1748)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1797)
	at dotty.tools.dotc.transform.Inlining$$anon$1.traverse(Inlining.scala:53)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1796)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1796)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.fold$1(Trees.scala:1660)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1662)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1755)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1797)
	at dotty.tools.dotc.transform.Inlining$$anon$1.traverse(Inlining.scala:53)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1796)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1796)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1752)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1797)
	at dotty.tools.dotc.transform.Inlining$$anon$1.traverse(Inlining.scala:53)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1796)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.apply(Trees.scala:1796)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.fold$1(Trees.scala:1660)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.apply(Trees.scala:1662)
	at dotty.tools.dotc.ast.Trees$Instance$TreeAccumulator.foldOver(Trees.scala:1761)
	at dotty.tools.dotc.ast.Trees$Instance$TreeTraverser.traverseChildren(Trees.scala:1797)
	at dotty.tools.dotc.transform.Inlining$$anon$1.traverse(Inlining.scala:53)
	at dotty.tools.dotc.transform.Inlining.checkPostCondition(Inlining.scala:54)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted$$anonfun$1(TreeChecker.scala:415)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedUnadapted(TreeChecker.scala:415)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3274)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:3278)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typed(TreeChecker.scala:381)
	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:3389)
	at dotty.tools.dotc.transform.TreeChecker.check(TreeChecker.scala:129)
	at dotty.tools.dotc.transform.TreeChecker.run(TreeChecker.scala:109)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:354)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:360)
	at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:315)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1 [...]

2024-02-06 16:23 UTC, yilinwei commented on tests/pos/byname-inline.scala
> +  inline def isEmpty: Boolean = false
This only seems to be a problem when `isEmpty` returns a literal, or calls a function returning a literal type.

2024-02-07 00:08 UTC, yilinwei commented on tests/pos/byname-inline.scala
> +final class ByName2(val x: Int) extends AnyVal:
This case actually produces valid scala code with `-Ycheck:all` disabled.

2024-02-07 10:04 UTC, nicolasstucki requested changes

2024-02-07 10:04 UTC, nicolasstucki commented on tests/pos/byname-inline.scala
> +  inline def isEmpty: Boolean = x == 1
I do not believe we have a way to make this work. The JVM would probably inline these calls anyway.

2024-02-07 10:27 UTC, yilinwei commented on compiler/src/dotty/tools/dotc/transform/Inlining.scala
> +               // will inline them at a later stage.
Could we inline where the calls are introduced then i.e. during the pattern matcher? 

Or do we need to do something like the trick that has been done with the unapply body currently and reduced in the `InlinePatterns` stage?

2024-02-07 10:31 UTC, nicolasstucki commented on compiler/src/dotty/tools/dotc/transform/Inlining.scala
> +               // will inline them at a later stage.
> Could we inline where the calls are introduced then i.e. during the pattern matcher?

That can be problematic. The code that is inlined assumes that we have not been transformed by the phases that come after inlining (and before pattern matching).

> Or do we need to do something like the trick that has been done with the unapply body currently and reduced in the InlinePatterns stage?

That trick will not work well for name-based pattern matching.

2024-02-07 10:33 UTC, nicolasstucki commented on compiler/src/dotty/tools/dotc/transform/Inlining.scala
> +               // will inline them at a later stage.
If you really need to remove the code that you generate in https://github.com/lampepfl/dotty/pull/19577 we might need another way. Maybe a possible approach is to change the pattern matcher to do something specific for methods on records.

2024-02-07 12:58 UTC, sjrd commented on compiler/src/dotty/tools/dotc/transform/Inlining.scala
> +               // will inline them at a later stage.
It's a spec change anyway. Whether because you're synthesizing stuff that's not there, or because you change pattern matching logic.

2024-02-07 13:01 UTC, yilinwei commented on compiler/src/dotty/tools/dotc/transform/Inlining.scala
> +               // will inline them at a later stage.
I did not realise that - in which case let me investigate the pattern matcher changes required and put together a proposal.

2024-02-09 23:51 UTC, closed without merging