Add GADT symbols when typing typing-ahead lambda bodies
lampepfl/dotty pull request #19644
Opened 2024-02-07 22:52 UTC by dwijnand

Fixes #19570

2024-02-19 16:18 UTC, smarter requested changes

2024-02-22 20:23 UTC, smarter approved these changes

2024-02-22 20:24 UTC, smarter commented
What's the correct way to request a backport of this to 3.4.1-RC2?

2024-02-22 23:10 UTC, merged

2024-02-23 01:45 UTC, smarter commented
Because it fixes a regression. I don't think backporting fixes should require delaying the release: Rust does backport and never delays their releases (https://doc.rust-lang.org/book/appendix-07-nightly-rust.html), but I guess if this is our policy currently then not much point in backporting yeah.

2024-02-23 09:34 UTC, dwijnand commented
Good points.