Cosmetic adjustments in syntax
lampepfl/dotty pull request #9806
Opened 2020-09-16 08:35 UTC by kpbochenek

mainly indenting match-case code:
```scala
expr match {
  case cond =>
     expr1   // indenting it to not align with case
}
```
Looks more like dotty where case block must be indented.

2020-09-16 09:59 UTC, tgodzik requested changes
The changes here are only cosmetic from what I see, but I would revert a couple of weird formatting choices.

2020-09-16 09:59 UTC, tgodzik commented on compiler/src/dotty/tools/backend/jvm/BCodeBodyBuilder.scala
> +    private def genMatch(tree: Match): BType = tree match { case Match(selector, cases) =>
Can we revert this change?

2020-09-16 09:59 UTC, tgodzik commented on compiler/src/dotty/tools/backend/jvm/BCodeSyncAndTry.scala
> +    def genLoadTry(tree: Try): BType = tree match { case Try(block, catches, finalizer) =>
Also this?

2020-09-16 09:59 UTC, tgodzik commented on compiler/src/dotty/tools/backend/jvm/BCodeBodyBuilder.scala
> +    def genWhileDo(tree: WhileDo): BType = tree match { case WhileDo(cond, body) =>
Can we revert this?

2020-09-17 13:23 UTC, nicolasstucki commented
We should not do these formatting changes on the backend. It will make it harder to port commits from the scala2 backend as it will make the diff much harder to read. We should only do this once the backend is up to date.

2020-09-17 13:24 UTC, nicolasstucki requested changes
Please revert the changes to the backend. Sorry about that.

2020-09-17 13:31 UTC, kpbochenek commented
okay I will close this and move other changes to different PR.

2020-09-17 13:31 UTC, closed without merging